### ISSUE TITLE
JPEG to DICOM

### ISSUE THREAD

**Issue by costabs** [horosproject/horos#100]
Horos 1.1.7 running on OS X 10.11.3

After selecting JPEG images in the plugin’s window, and clicking Choose, nothing happens.
This issue was solved with a nightly build version of horos in a previous post but the links are dead.
Con you resend the links?

**Comment by fvpolpeta** [comment]
This has been addressed by the version 2.0.0 of Horos, which is now public as a Release Candidate. You can download it from the website.
