### ISSUE TITLE
New ROIs drawn in 2D Viewer are not preserved in DB if Quit is performed to close viewer.

### ISSUE THREAD

**Issue by jensen0914** [horosproject/horos#105]
To reproduce:
1) Launch Horos and open any image in 2D viewer.
2) Draw 1 or more ROIs.
3) Select Horos->Quit to exit Horos.
4) Re-launch Horos and open same image in 2D viewer. ROIs are not displayed.

In order to make sure the ROIs are preserved, the 2D viewer must be closed by using the Database button. I would expect the Quit method should also preserve new ROIs.

**Comment by fvpolpeta** [comment]
Hi,

Thanks for reporting this.

Please, check if the build below solves the problem:

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightlyRC4_20160613.dmg

BR

**Comment by jensen0914** [comment]
This RC4_20160613 build fixes this issue. Thanks!
