### ISSUE TITLE
auto query/retrieve window not working in 2.0 RC3

### ISSUE THREAD

**Issue by pixelmixture** [horosproject/horos#108]
hi,

when i install horus 2.0 RC3, auto query/retrieve works ... than i quit and reload horos and it's not working anymore ....

**Comment by fvpolpeta** [comment]
Hey,

Try out this build and let us know if it works.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightlyRC4_20160613.dmg

**Comment by pixelmixture** [comment]
it works

**Comment by fvpolpeta** [comment]
Try this build and let us know about any AutoQR issues:

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightlyRC5_20160621.dmg

Tks

**Comment by venkatsrinivas** [comment]
what is AutoQR

**Comment by fvpolpeta** [comment]
auto query/retrieve function

**Comment by venkatsrinivas** [comment]
Another issue:
In the installed plugins dialog box / form, there is uninstall button, assume the dialog box / form is empty and i click on the uninstall button, then at that time, it doesn't give me a Alert message box with the message "there are no plugins. please have at least one plugin to uninstall". instead it shows me a message box with the message "do you want to uninstall the plugin" i think this message box should not be shown
