### ISSUE TITLE
MacOSX 10.9.5 can't run Horos

### ISSUE THREAD

**Issue by ReneLaqua** [horosproject/horos#109]
I can't start Horos 2.0 with MacOSX 10.9.5. Are there fundamental changes in this new version? I downloaded the source code and saw that the "Deployment Target" is still 10.8

**Comment by fvpolpeta** [comment]
Hi,

The most recent versions are only buildable in El Capitan with XCode 7.x. The target SDK of each target is 10.11.

Deployment target is kept 10.8 but it has no direct effect, except avoiding XCode issues that we are working to resolve.

Regards
