### ISSUE TITLE
JPEG LS DICOM compression issue

### ISSUE THREAD

**Issue by ky-tech-guy** [horosproject/horos#11]
When I compress dicom images with the JPEG LS compression scheme, the images become blank. I tried changing the windowing and this did fix the problem. Then when I restart horse, the image series won't load.  See the image below for details.
![screen shot 2015-04-09 at 1 11 39 pm](https://cloud.githubusercontent.com/assets/10901615/7072400/1629447a-deba-11e4-8254-1356aaac5c21.jpg)

**Comment by fvpolpeta** [comment]
Thanks for reporting. 
This is going to be fixed in version 1.0.5.

**Comment by ky-tech-guy** [comment]
Thanks for all your hard work.  Horos is continuing to evolve into an elite DICOM solution.

**Comment by fvpolpeta** [comment]
Preparing release of version  1.0.5 where this is fixed.
