### ISSUE TITLE
Compiling needs XCode 7.0

### ISSUE THREAD

**Issue by ReneLaqua** [horosproject/horos#110]
I need XCode 7 to compile the new source code, which is only available for MacOS 10.11 (El Capitan). Compling stops with the following error:
FlyThru.xib - This version does not support box content view. Open this document with XCode 7 or later.

Why isn't the source code backward compatible? I use XCode 6.1.1.

**Comment by fvpolpeta** [comment]
Hi,

The most recent versions are only buildable in El Capitan with XCode 7.x. The target SDK of each target is 10.11.

Regards

**Comment by venkatsrinivas** [comment]
if i am wrong correct me, but i see a new version of MAC OS at apple developer so need to know when would the Horos version come up Thanks

**Comment by DD-P** [comment]
I'd just like to comment in support of keeping the build up to date with the current (released) OS and Xcode.

Prior to Horos and the immediately preceding projects it was difficult to keep an older build environment available.  Apple quite aggressively advances new SDKs, which is generally considered a good thing, though it becomes harder to catch up when the project is substantially behind the current toolchain.

(I can't speak for @fvpolpeta but I would anticipate Horos project support for building under macOS 10.12 / Xcode 8 would follow their official release later in the year.  In the meantime I would expect the compiled application would be compatible with 10.12, though no doubt we will check with the betas and report any issues.)

**Comment by fvpolpeta** [comment]
The initial test shows that Horos runs properly in Sierra (macOS 10.12), but the building in XCode 8 is failing. 

Since both are incipient alpha/beta releases, we will be waiting a bit more to go deeper in this new environment. Anyway, any help from you guys and from all the community is very welcome.

Tks in advance.

**Comment by venkatsrinivas** [comment]
Good to see Horos on Sierra

**Comment by venkatsrinivas** [comment]
Any possibility of Horos having Swift as the Lang in the near future

**Comment by DD-P** [comment]
A complete rewrite in Swift would be highly unlikely - it would be an entirely new project.  In time, some Swift code could be added I presume, but the Horos build requirements and code base seem complex enough already.

(This should be a separate question as it does not relate to the issue posted by @ReneLaqua).
