### ISSUE TITLE
problem with a toolbar in 2.0

### ISSUE THREAD

**Issue by sarmentofrancisco** [horosproject/horos#113]
Good afternoon, i made a download of a horos’s new version, bit i am with a problem in toolbar.

When i open the exam, the toolbar didn’t apear. I only see the toolbar with no icon to click.

**Comment by fvpolpeta** [comment]
Try in the upper menu go to Format=>Customize Toolbar, drag the default toolbar and check if can be restored.

[]'s

**Comment by sarmentofrancisco** [comment]
It was restored.
Thanks.
