### ISSUE TITLE
No windows open/draw

### ISSUE THREAD

**Issue by thomasdg** [horosproject/horos#114]
First time ever that I ran Horos, I had no problems.

Now when I start Horos I can see the database window. Any other window I try to open does nothing at all.
Selecting the Plugin manager from the plugin menu: nothing drawn on screen, but in de "Window" menu item, I do see the window listed. Opening an exam: the cursor changes to "level/window" cursor, but nothing is shown. Again, in the window menu item I can see the exam window listed.

When I command-tab to Horos from some other program, the Horos application does not get the focus.

Running on an up-to-date OS X 10.11.5 on a MBP 15".

**Comment by thomasdg** [comment]
After days of trying, I now choose "close window" from the Horos dock icon and everything seems to work again... Sorry for the bad bug report!

**Comment by thomasdg** [comment]
And again does not work anymore, even after the "work-around", so I re-open this bug...

**Comment by venkatsrinivas** [comment]
Hi

Can you attach the Screenshots

Regards,
Srini

**Comment by fvpolpeta** [comment]
Since there is no feedback, I'm closing the issue. If decide to opening it back, my suggestion is to launch Horos from the terminal and copy and paste the application output here.

Tks
