### ISSUE TITLE
Dicom Compression with JPEG 2000 Not Working

### ISSUE THREAD

**Issue by ky-tech-guy** [horosproject/horos#12]
When I try to compress a dicom dataset from uncompressed to JPEG 2000, nothing happens. This Feature works in Osirix 5.8.2. If you need an uncompressed dataset for testing let me know.
![screen shot 2015-04-08 at 10 29 51 pm](https://cloud.githubusercontent.com/assets/10901615/7072441/7b3b0af6-deba-11e4-8211-a5e2f28e9e75.jpg)

**Comment by fvpolpeta** [comment]
Hi, thanks for reporting. 
Which version of Horos are you using? In principle, that was fixed in 1.0.4, and 1.0.5 is going to fix JPEGLS compression/decompression.

**Comment by ky-tech-guy** [comment]
I was using Horos 1.0.3 at the time of this issue submission.  I tested Horos 1.0.4 and JPEG 2000 compression/decompression is working.  Thanks for fixing this issue.
