### ISSUE TITLE
Scrolling too slow

### ISSUE THREAD

**Issue by piauizao** [horosproject/horos#141]
Since a few days ago scrolling images in a series became a painful process. Very slow and, furthermore, the program often gets "stuck", then jumps to an image several numbers ahead within the same series while skipping the others, even with no other program running. Otherwise, Mac is working really fine.
Any thoughts? Is it just me?

**Comment by eleted** [comment]
Its a problem of new version of Horos - optimized for new macOS Sierra not for El Capitane. I had it too. solution: install any version below 2.0

**Comment by piauizao** [comment]
As I'll probably upgrade to Sierra, let's see how it works with the new OS.
Thanks, anyway!

**Comment by Toyisi** [comment]
Actually I also noticed erratic scroll speed using the trackpad with Horos 2.02.
Rolling back to Horos 2.0 solved the issue.

I don't know if 2.0 will work with Sierra.

**Comment by eleted** [comment]
Horos 2.0.0 RC5 works with Sierra but with a little bit fasting scrolling than with El Capitane

**Comment by piauizao** [comment]
Where can I find previous version of Horos for download?

Enviado do meu iPhone

**Comment by eleted** [comment]
https://yadi.sk/d/QpuYhRArvkuNS 
this is Horos 2.0.0 RC5.
here is Horos 1.1.17 (official site): https://www.horosproject.org/adaa7f5d1f33cb8ddd89fe300da7c2cd/

**Comment by piauizao** [comment]
New download available marked as "temporary workaround for unpredictable scrolling behavior in macOS Sierra". I'm gonna try it on.

**Comment by laiawake** [comment]
I have Horos 2.02 on Sierra. The scrolling speed is highly erratic on the trackpad. It's completely unusable.

**Comment by fvpolpeta** [comment]
Fixed and released. New version coming this week.

**Comment by efnikos2000** [comment]
Change mouse-trackpad settings on system preferences

**Comment by paulosecundo** [comment]
I am with the same problem. Scroll just freeze and start some slice after. How to solve this? I am using High Sierra right now and my Horos is the last version 2.2.0.

**Comment by brunocangussu** [comment]
even with the update horos 2.4.0, continues with the same problem. Will not anyone fix this?
i have a new macbook pro.

**Comment by fvpolpeta** [comment]
Hi -

Thanks for using Horos. Please, try the following Nightly build of Horos 3.0 and let us know your results.

https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180113.app.zip <https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180113.app.zip>

In case the problem persists we will be requesting more information.

Regards

Fauze

**Comment by brunocangussu** [comment]
Perfect!

**Comment by hozermd** [comment]
Hi,
I am using Macbook Air Retina, MacOS Mojave and Horos 4.0.0 RC1 and I have same problem. Scroll is too lag. I installed OsiriX Lite edition andI have not encountered this problem. Scroll is so smooth and fluent. How fix this problem. Thanks.

**Comment by happycute** [comment]
hello!
the latest version of Horos 3.3.6. as well as 4.0.0.  - scrolling images is horrible!
I mean, if there are 100 images in a series it's mostly fine, but when they are more then 500 it's lagging like hell!
I'm using high Sierra mid 2011 16 gigs of ram, ssd, 512 mb video and the machine running fine.
tried older versions - didn't help.
Osirix lite 11.0.2. is scrolling beautifully, no problem at all.
Please, help!
May be there are some steps to take to make it run more smoother?

**Comment by hozermd** [comment]
@happycute Hi
Yes, this problem has existed for many years. I think it's due to a mismatch with the new MacOS versions. It has nothing to do with the power of the hardware. There's a trick point for this issue. Please use "3D Viewer-->2D Orthogonal MPR", scrooling relatively smooth. Working this way is more limited, but this method works.

**Comment by happycute** [comment]
Will try it, thanks. How about OS downgrading? For instance to Sierra, do
you think it'll help?

чт, 30 апр. 2020 г., 23:08 Hamza <notifications@github.com>:

**Comment by hozermd** [comment]
@happycute Unfortunately I don't know, I have not tried.

**Comment by happycute** [comment]
It works fine on os el capitan

пт, 1 мая 2020 г., 00:00 Hamza <notifications@github.com>:

**Comment by happycute** [comment]
It works fine on os el Capitan even with 8 gigs of ram

пт, 1 мая 2020 г., 00:04 Constantine Krokhmal <
constantine.krokhmal@gmail.com>:

**Comment by happycute** [comment]
I don't want to downgrade os though.
any suggestions as to making horos more smooth on high Sierra please

**Comment by paulosecundo** [comment]
The only solution is 2D orthogonal. I have same problem since 2018.

Em sex., 1 de mai. de 2020 às 05:37, happycute <notifications@github.com>
escreveu:
