### ISSUE TITLE
cannot start Horos 

### ISSUE THREAD

**Issue by hobieddb** [horosproject/horos#147]
I  am running mAC OS 10.8.5   and I downloaded  Horos 1.1.7, but The application does not open. 
No, osirix  is no to open at the same time, and I receive a message I am attaching.

If I shut down  the computer  I can't  because HOROS  appear to be running in the list of application  and I need to force quit it 

![Uploading PastedGraphic-1.jpeg…]()
![pastedgraphic-2](https://cloud.githubusercontent.com/assets/23219409/19939061/aae0e740-a127-11e6-8290-4123a365d39d.jpeg)

even if   from the  list  of application  shown  when  I press  tab and  command  HROs  is not  open 

HELP ME PLEASE :)

**Comment by fvpolpeta** [comment]
Possibly this is happening due to some security update Apple made to 10.8.5.

We are no longer giving any support on 10.8.x. We strongly advise you to update to Sierra and start using Horos 2.1.x

Tks
