### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by alealla** [horosproject/horos#153]
The app is crashing when I choose to see a reformatted serie, but it's working with regular volume of CT.

**Comment by alealla** [comment]
Process:               Horos [9848]
Path:                  /Applications/Horos.app/Contents/MacOS/Horos
Identifier:            com.horosproject.horos
Version:               2.1.0 (20161120)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Horos [9848]
User ID:               501

Date/Time:             2016-11-26 11:54:51.272 -0200
OS Version:            Mac OS X 10.12.1 (16B2657)
Report Version:        12
Anonymous UUID:        57269BCA-C06A-077A-FD20-5B0F5C1F9030

Sleep/Wake UUID:       CC49C08B-EA0C-4D42-BF0E-5ABBE2CA2360

Time Awake Since Boot: 27000 seconds
Time Since Wake:       11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000010c585000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x10c585000:
    MALLOC_LARGE           000000010c4c5000-000000010c585000 [  768K] rw-/rwx SM=PRV  
--> 
    MALLOC_LARGE           000000010c588000-000000010c608000 [  512K] rw-/rwx SM=COW  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.macrad.dcmframework       	0x0000000104264b2c ProcessTransformed<TransformNone<unsigned char> >::DecodeTransform(void const*, void*, int, int) + 194
1   com.macrad.dcmframework       	0x0000000104266133 ProcessTransformed<TransformNone<unsigned char> >::NewLineDecoded(void const*, int, int) + 115
2   com.macrad.dcmframework       	0x000000010427fa80 JlsCodec<LosslessTraitsT<unsigned char, 8l>, DecoderStrategy>::DoScan() + 504
3   com.macrad.dcmframework       	0x0000000104267b62 JlsCodec<LosslessTraitsT<unsigned char, 8l>, DecoderStrategy>::DecodeScan(std::auto_ptr<ProcessLine>, JlsRect const&, ByteStreamInfo*, bool) + 146
4   com.macrad.dcmframework       	0x0000000104260e09 JpegMarkerReader::Read(ByteStreamInfo) + 455
5   com.macrad.dcmframework       	0x0000000104261df3 JpegLsDecode + 179
6   com.macrad.dcmframework       	0x00000001041d9037 -[DCMPixelDataAttribute convertJPEGLSToHost:] + 247
7   com.macrad.dcmframework       	0x00000001041dfda2 -[DCMPixelDataAttribute decodeFrameAtIndex:] + 2530
8   Horos                         	0x0000000101c7ab87 -[DCMPix loadDICOMDCMFramework] + 10519
9   Horos                         	0x0000000101c7cf22 -[DCMPix CheckLoadIn] + 898
10  Horos                         	0x0000000101c80381 -[DCMPix CheckLoad] + 65
11  Horos                         	0x0000000101c6f1d6 -[DCMPix wl] + 22
12  Horos                         	0x0000000101b67f05 -[DCMView setIndexWithReset::] + 949
13  Horos                         	0x0000000101ede827 -[BrowserController previewSliderAction:] + 2951
14  Horos                         	0x0000000101edd4e3 -[BrowserController initAnimationSlider] + 1187
15  Horos                         	0x0000000101edf378 -[BrowserController matrixPressed:] + 568
16  Horos                         	0x0000000101ed9358 -[BrowserController findAndSelectFile:image:shouldExpand:extendingSelection:] + 2808
17  Horos                         	0x0000000101b0ea17 -[ViewerController changeImageData::::] + 7719
18  Horos                         	0x0000000101eef154 -[BrowserController openViewerFromImages:movie:viewer:keyImagesOnly:tryToFlipData:] + 13012
19  Horos                         	0x0000000101edc147 -[BrowserController loadSeries:::keyImagesOnly:] + 215
20  Horos                         	0x0000000101af6d10 -[ViewerController loadSelectedSeries:rightClick:] + 2000
21  com.apple.Foundation          	0x00007fff997f6c88 __NSFireDelayedPerform + 417
22  com.apple.CoreFoundation      	0x00007fff97d78e84 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
23  com.apple.CoreFoundation      	0x00007fff97d78b13 __CFRunLoopDoTimer + 1075
24  com.apple.CoreFoundation      	0x00007fff97d7866a __CFRunLoopDoTimers + 298
25  com.apple.CoreFoundation      	0x00007fff97d70231 __CFRunLoopRun + 2081
26  com.apple.CoreFoundation      	0x00007fff97d6f7b4 CFRunLoopRunSpecific + 420
27  com.apple.HIToolbox           	0x00007fff972ff2ac RunCurrentEventLoopInMode + 240
28  com.apple.HIToolbox           	0x00007fff972ff0e1 ReceiveNextEventCommon + 432
29  com.apple.HIToolbox           	0x00007fff972fef16 _BlockUntilNextEventMatchingListInModeWithFilter + 71
30  com.apple.AppKit              	0x00007fff959016cd _DPSNextEvent + 1093
31  com.apple.AppKit              	0x00007fff96078830 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2730
32  com.apple.AppKit              	0x00007fff958f606d -[NSApplication run] + 926
33  com.apple.AppKit              	0x00007fff958c0983 NSApplicationMain + 1237
34  libdyld.dylib                 	0x00007fffad079255 start + 1

Thread 1:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fffad1a7f4e __select + 10
1   com.apple.CoreFoundation      	0x00007fff97dab909 __CFSocketManager + 729
2   libsystem_pthread.dylib       	0x00007fffad290aab _pthread_body + 180
3   libsystem_pthread.dylib       	0x00007fffad2909f7 _pthread_start + 286
4   libsystem_pthread.dylib       	0x00007fffad290221 thread_start + 13

Thread 2:: DICOM Store-SCP
0   libsystem_kernel.dylib        	0x00007fffad1a7f4e __select + 10
1   Horos                         	0x000000010206f21a ASC_associationWaiting(T_ASC_Network*, int) + 138
2   Horos                         	0x0000000101d6b2e3 DcmQueryRetrieveSCP::waitForAssociation(T_ASC_Network*) + 99
3   Horos                         	0x0000000101d4fe26 -[DCMTKQueryRetrieveSCP run] + 4310
4   Horos                         	0x0000000101ab4947 -[AppController startSTORESCP:] + 519
5   com.apple.Foundation          	0x00007fff9979c30d __NSThread__start__ + 1243
6   libsystem_pthread.dylib       	0x00007fffad290aab _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffad2909f7 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffad290221 thread_start + 13

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fffad1a041a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fffad19f867 mach_msg + 55
2   com.apple.CoreFoundation      	0x00007fff97d70ae4 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation      	0x00007fff97d6ff61 __CFRunLoopRun + 1361
4   com.apple.CoreFoundation      	0x00007fff97d6f7b4 CFRunLoopRunSpecific + 420
5   com.apple.AppKit              	0x00007fff95a4e7d4 _NSEventThread + 205
6   libsystem_pthread.dylib       	0x00007fffad290aab _pthread_body + 180
7   libsystem_pthread.dylib       	0x00007fffad2909f7 _pthread_start + 286
8   libsystem_pthread.dylib       	0x00007fffad290221 thread_start + 13

Thread 4:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	0x00007fffad1a041a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fffad19f867 mach_msg + 55
2   com.apple.CoreFoundation      	0x00007fff97d70ae4 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation      	0x00007fff97d6ff61 __CFRunLoopRun + 1361
4   com.apple.CoreFoundation      	0x00007fff97d6f7b4 CFRunLoopRunSpecific + 420
5   com.apple.CFNetwork           	0x00007fff96f32334 +[NSURLConnection(Loader) _resourceLoadLoop:] + 313
6   com.apple.Foundation          	0x00007fff9979c30d __NSThread__start__ + 1243
7   libsystem_pthread.dylib       	0x00007fffad290aab _pthread_body + 180
8   libsystem_pthread.dylib       	0x00007fffad2909f7 _pthread_start + 286
9   libsystem_pthread.dylib       	0x00007fffad290221 thread_start + 13

Thread 5:
0   libsystem_pthread.dylib       	0x00007fffad290204 start_wqthread + 0

Thread 6:
0   libsystem_kernel.dylib        	0x00007fffad1a84e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffad2907b5 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffad290211 start_wqthread + 13

Thread 7:
0   libsystem_kernel.dylib        	0x00007fffad1a84e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffad2907b5 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffad290211 start_wqthread + 13

Thread 8:
0   libsystem_kernel.dylib        	0x00007fffad1a84e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffad2907b5 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffad290211 start_wqthread + 13

Thread 9:
0   libsystem_pthread.dylib       	0x00007fffad290204 start_wqthread + 0

Thread 10:
0   libsystem_kernel.dylib        	0x00007fffad1a84e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffad2907b5 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffad290211 start_wqthread + 13

Thread 11:
0   libsystem_kernel.dylib        	0x00007fffad1a84e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffad2907b5 _pthread_wqthread + 1426
2   libsystem_pthread.dylib       	0x00007fffad290211 start_wqthread + 13

Thread 12:
0   libsystem_pthread.dylib       	0x00007fffad290204 start_wqthread + 0
1   ???                           	0x00000000000001ee 0 + 494

Thread 13:
0   libsystem_pthread.dylib       	0x00007fffad290204 start_wqthread + 0
1   ???                           	0x0000000000014343 0 + 82755

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000010c584ffd  rbx: 0x00006080006bfda0  rcx: 0x0000000000000200  rdx: 0x000000010c584a00
  rdi: 0x00006080006bfda0  rsi: 0x00007fa2c7081200  rbp: 0x00007fff5e15b610  rsp: 0x00007fff5e15b5f8
   r8: 0x0000000000000204   r9: 0x0000000000000001  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x00000000000001ff  r13: 0x0000000000000003  r14: 0x00007fa2c70e8e00  r15: 0x0000608000a23ee0
  rip: 0x0000000104264b2c  rfl: 0x0000000000010246  cr2: 0x000000010c585000
  
Logical CPU:     2
Error Code:      0x00000006
Trap Number:     14

**Comment by fvpolpeta** [comment]
Please, describe the whole process you are trying to do and attach a series sample for enabling us to reproduce the problem.

Tks

**Comment by alealla** [comment]
When I click on the reformatted serie,
[reformat dont work.zip](https://github.com/horosproject/horos/files/620251/reformat.dont.work.zip)
 the Horos app crashes.

**Comment by alealla** [comment]
The volume serie is OK.
[volume works.zip](https://github.com/horosproject/horos/files/620255/volume.works.zip)

**Comment by alealla** [comment]
A reformatted serie that doesn't crash.
Thanks
[reformat dont work.zip](https://github.com/horosproject/horos/files/620261/reformat.dont.work.zip)
.

**Comment by fvpolpeta** [comment]
Please, check zip files and confirm that you uploaded the problematic series. All these zip files worked in Horos for me.

Regads

**Comment by alealla** [comment]
Decompressing images after retrieving worked. Thanks for your help.
