### ISSUE TITLE
Report PDF

### ISSUE THREAD

**Issue by alealla** [horosproject/horos#158]
PDF report conversion stopped working in OsX 10.12.2.

**Comment by houstonian** [comment]
I think Report conversion to PDF works okay. I have tried with TextEdit and Word. But I have noticed that, at least with TextEdit, it seems like DICOM PDF Conversion is not working. It creates a blank image.

**Comment by alealla** [comment]
It does not work anymore with pages.

**Comment by houstonian** [comment]
For me, Pages isn't working at all. **In terms of Report PDF we should clarify if we mean purely generating a PDF vs a PDF DICOM.**  Again, I can't even use Pages to create a report at all ...regardless of format. I have also noticed that for TextEdit my template options are limited to 1 template.

**Comment by alealla** [comment]
I have been using pages in the last 4 years. After finishing the report, I change the status to validated. After validated, OsiriX/ Horos always converted the pages report to a PDF dicom image, until the last OS X update (Sierra). 
I tested OsiriX and stopped working too, but they fixed after an update (something like 8.0 to 8.01), but I don't use OsiriX anymore. 
I suppose I will have to downgrade OS X.

**Comment by alealla** [comment]
If you need to use pages, let me
Know so I can help you.
