### ISSUE TITLE
Report PDF 

### ISSUE THREAD

**Issue by alealla** [horosproject/horos#168]
How to fix report PDF conversion after validating  in OS X Sierra?

**Comment by alealla** [comment]
Report PDF with pages is back with OS X 10.12.4.

**Comment by houstonian** [comment]
alealla did you find a solution? I do need help with pages and getting different templates.

**Comment by alealla** [comment]
[pages template horos.pdf](https://github.com/horosproject/horos/files/918253/pages.template.horos.pdf)

Follow this pdf.

**Comment by houstonian** [comment]
Thank you. This was really helpful!  Do you know why can't the newer version of Pages be used to save the templates. I know it doesn't work well right now, but wondering if it should be posted as an issue that needs some attention.

**Comment by alealla** [comment]
OsiriX changed this recently, but it was not a big deal. Not a functional change. The only one downside is to convert the template file to 09 format, which is a minimal effort.
