### ISSUE TITLE
question about os compatibility

### ISSUE THREAD

**Issue by tessus** [horosproject/horos#171]
I understand that making SW available for OS releases which are older than 3-5 years can be problematic, but I fail to see the reason that 10.12 is needed for Horos 2.1.1.

Are you using special features of 10.12 or did you just compile it for 10.12?
(10.12 did not have any groundbreaking additions to the OS)

Any chance you could use 10.11 as the deployment target?

**Comment by fvpolpeta** [comment]
Good comment Tessus -

In principle, I could keep Horos being built for version 10.8. A few reasons why I constantly have to migrate:

1) I don't have a specific Horos Dev. Station - and I need my two Macs to be updated.

2) The only issues I faced are related to the App Signature System. I don't remember it was specifically for 10.10 or 10.11 - but I wasn't able to sign Apps with previous versions of the XCode

3) New XCode versions usually go deprecating older SDK versions - that will happen with 10.11 - which I guess doesn't come with newer XCode

**Comment by tessus** [comment]
Thanks for the info.

As far as I know there should not be an issue to set the deployment target to 10.11 on the latest Xcode on 10.12.

I usually try to upgrade as quicky as possible, but sometimes there are reasons why I (or other people can't upgrade to the latest OS). Even, if a certain SDK does not come with Xcode, you can still install them [manually](https://github.com/phracker/MacOSX-SDKs).

However, you do not need the Base SDK for 10.11 to set the deployment target to 10.11.

**Comment by tessus** [comment]
I've compiled the latest commit point with deployment target 10.11 (on 10.11 with Xcode 8.2.1) and everything seems to be in order.
If you are interested, you can try running it on 10.12.
https://evermeet.cx/pub/macosx/Horos/Horos-2.1.1.zip

**Comment by fvpolpeta** [comment]
Thanks - I'm evaluating the possibility of setting up a 10.11 station in order to have Horos backward compatible with 10.11.

Thanks a lot. I will be back to you in a near future (couple of weeks)

**Comment by tessus** [comment]
That's what I meant: you don't have to. You can still use your 10.12 development system. You only have to change the following 2 things and the binaries will run on 10.11+:

![xcode1](https://cloud.githubusercontent.com/assets/223439/24054150/9e7248a6-0b11-11e7-91da-1dc12d177956.jpg)

![xcode2](https://cloud.githubusercontent.com/assets/223439/24054169/aa6d0222-0b11-11e7-9b9f-e377f1272e6b.jpg)

(e.g. you could change that value to 10.10 or 10.9 as well. The only reason why it wouldn't work for lower OS versions is, if you used features and functions not available in earlier versions.

**Comment by boskar** [comment]
It works! I'm currently using Your build in my enviroment.

**Comment by tessus** [comment]
After 3 years we can close this.
