### ISSUE TITLE
magnification lens 

### ISSUE THREAD

**Issue by efnikos2000** [horosproject/horos#172]
Hello, 
the magnification lens has a static zoom percentage without possibility of modification.

**Comment by kaleemullahabid** [comment]
plz solve this static shift zoom issue with adjustable zoom option (+-)

**Comment by brizolara** [comment]
Hi all,

Please try out version 3.1 RC1, which includes improved loupe:

https://horosproject.org/horos-content/Horos3.1.0RC1.dmg

There size of glass and zoom percentage are controlled by up/down/-/+ keys.
This got implemented in #335
