### ISSUE TITLE
Horos crashes when opening certain images

### ISSUE THREAD

**Issue by ky-tech-guy** [horosproject/horos#18]
When I tried to open certain series from a dicom set I downloaded from the Osirix website, Horos crashes.  See the attached image for details.  Also the dicom set can be found at the following link http://www.osirix-viewer.com/datasets/DATA/MELANIX.zip
![screen shot 2015-04-30 at 7 21 37 pm](https://cloud.githubusercontent.com/assets/10901615/7424411/bd197718-ef6e-11e4-9bea-cb772e6cf2e9.jpg)

**Comment by fvpolpeta** [comment]
Thanks a lot for reporting that.
This is already fixed. Horos will not crash with that series in the next release.
