### ISSUE TITLE
Which is the best license model for Horos?

### ISSUE THREAD

**Issue by fvpolpeta** [horosproject/horos#217]
Dear Horos Users and Developers –

As one of the Horos contributors and curators, I want firstly to thank you all for your adoption of Horos, and the donations you have been making to the project. As you may know, we have over 80,000 people using the product at this time, growing by over 5,000 per month. Your loyalty and help is appreciated.

The main reason I’m writing you is to hear your opinion and start a discussion of what could be an improved license model for Horos. Many plugin developers have contacted me saying they would love to contribute proprietary libraries and plugins, but the Horos GPL license is too restrictive and would lead them to have to release their source-code into the public domain. According to the GPL license, and in simple terms, when binary code is linked statically or dynamically to a GPL code project, the binary needs to have the source code released under the GPL terms. I have seen different interpretations but, all in all, this leads to a quicksand territory.

The OsiriX project was licensed originally as GPL too; later it switched to LGPL. As a long-term OsiriX adopter, I evidenced a considerable number of plugins becoming available in OsiriX and some of them with proprietary code. Even OsiriX had some third-party codecs integrated to it, which added significant improvement to image decoding performance. That was mainly possible because of the LGPL transition the OsiriX maintainers made effective.

So why is Horos not LGPL?

First of all, the fact Horos is not LGPL is not related to any private or commercial intention of our main sponsor, Purview.  Purview already confirmed, and emphasized, that the company has no reason/intention to make Horos a closed-source project. Even if they were to pursue FDA, CE or other regulatory approval, they could do so with an open source project.  In fact, we hope someday they do head in that direction.

That said, and back to our question “So why is Horos’ license not LGPL?”. The GPL licensing Purview has chosen is based upon the notations that they found in the open source code at the time of their fork.  Even though OsiriX had clearly stated that the open source code license had changed to LGPL, they did not update all the source code to reflect that.  In fact, Purview wasn’t convinced that OsiriX had sufficient authorization from each of its contributors to change from GPL to LGPL (which would have been required to make this change). So they seem to be stuck in a quandary.  The Horos Project wants to abide by FOSS licensing conventions but is unsure of whether the original copyright holders of the GPL code would agree to the change.

That’s where we would like to hear your comments.  Which is the best license model for Horos? LGPL? Which are the implications of this transition? Are any of you copyright holders in any of the former OsiriX modules?  Do you know of any who would be impacted by such a change.

In advance, I thank all the users, developers, and the license experts that can shed some light or opinion to this discussion.

Best Regards

Fauze Polpeta

**Comment by aglv** [comment]
As discussed, I'd go for LGPL.
We should isolate the components that are GPL and replace/remove them: PowerCrust (seems to be unused anyway), AYDicomPrint (is closed-source, we only have binaries from Aycan), iChatTheatre, ...

**Comment by JoaoSantinha** [comment]
First I would like to thank all the developers involved for their effort to maintain and further develop this amazing software.
In my opinion, the license model for Horos should be at least LGPL. This might lead to more active development of Horos by the developers of plugins.

**Comment by fvpolpeta** [comment]
Thanks for the feedback guys. We are considering set the project as LGPL.

Are you aware of someone that is claiming (or could claim) for code in Horos as proprietary or not compatible with LGPL.

We are reviewing file headers stated as GPL to confirm they are GPL indeed or just missed the LGPL update when OsiriX went LGPL.

In terms of components, Alessandro mentioned PowerCrust, and others are binaries, which in turn, seems to be more aligned to the LGPL model. 

Any of you have something else to share?

Thanks in advance

Fauze
