### ISSUE TITLE
Building Horos

### ISSUE THREAD

**Issue by fvpolpeta** [horosproject/horos#221]
Dear Developers -

Horos building system has been refactored and you may have problems getting Horos built from the master branch. 

A branch (horos_2.0) was created and it includes a buildable version of Horos.

Thanks for your cooperation.

Fauze

**Comment by aglv** [comment]
So, things seem to be fine now. If you have problems after pulling the new commits, the easy solution is to simply clone the whole repository again. The build scripts will take care of submodules.
If you do encounter these problems after updating a pre-cloned repository and you find another solution that doesn't require a re-clone, please post here.
