### ISSUE TITLE
pages fails to create report with horos

### ISSUE THREAD

**Issue by sand177** [horosproject/horos#222]
Hi, i am unable to create report while using pages on horos.
Please help.

<img width="424" alt="screen shot 2017-11-13 at 12 53 40" src="https://user-images.githubusercontent.com/33618093/32714097-3e60304e-c872-11e7-98a2-23bd1c76ba4c.png">

**Comment by brizolara** [comment]
Hi,

Thanks for reporting this.

We fixed it and it will be in the next release - probably Monday.

All the best,

Tiago

**Comment by fvpolpeta** [comment]
This is fixed in Horos 2.3.0, which is released and available for download at:

https://www.horosproject.org/wp-content/uploads/downloads/Horos2.3.0.dmg

Thanks
