### ISSUE TITLE
Bug: Import Dialog Window not closing when importing from CD

### ISSUE THREAD

**Issue by azankl** [horosproject/horos#227]
When I mount a CD with DICOM files on it, Horos pops up a dialogue asking me if I want to copy or browse these files. If I choose copy, Horos starts copying the files to my Horos database, but the dialogue window does not close. I think that's a bug.
I am using Horos 2K v.2.2.0 on a MacBook Pro running macOS 10.13.

**Comment by aglv** [comment]
Not sure, but I think I already fixed this and it should be OK in the next release. However, as a temporary workaround, go to the Horos CD/DVD preferences and choose to always copy, so the dialog won't appear and you won't be stuck.

**Comment by aglv** [comment]
Could you tell us if this is still happening with Horos 2.3.0?

**Comment by azankl** [comment]
Yes, still the same in Horos 2.3.0. I can still copy the images into Horos, but the dialog does not disappear despite the images having been copied. I can click on the main Horos window to cover up the dialog and continue working, but its still a bug and confusing. Clicking ‘Ignore’ also does not dismiss the dialog.

I am actually importing the DICOM images from an .iso image of the original CD (dont have a CD drive, so need to create .iso images on a different computer first). Not sure if that makes a difference? Would Horos normally eject the CD after importing the files and because it can’t eject, it keeps the dialog open? Just an idea…

Thanks for your help!
Andreas

**Comment by fvpolpeta** [comment]
Hi  –

Please, could you test this release candidate of Horos 2.4 and confirm the CD importing issue is solved:

https://www.horosproject.org/wp-content/uploads/rc/Horos2.4_RC.app.zip

Thanks in advance

Fauze

**Comment by horosproject** [comment]
Please download the Horos 2.4.0 which became the official release and let us know if the issue is fixed. 

https://www.horosproject.org/download/

Fauze

**Comment by azankl** [comment]
Hi Fauze,

CD importing works normally now in 2.4.0! Thanks for fixing this!
Andreas

**Comment by fvpolpeta** [comment]
You are welcome. Thanks for using Horos.

Also, many thanks to Tiago Brizolara for investing his time and proposing the fix.

Enjoy Horos - Now, LGPL licensed.
