### ISSUE TITLE
Swiss magnification tool faulty

### ISSUE THREAD

**Issue by kaleemullahabid** [horosproject/horos#245]
osirix has better swiss magnification tool which has +- size adjustability. where as horos doesn't has kindly improve it. very small swiss magnification tool. not useful

**Comment by DD-P** [comment]
This looks to have been fixed in #335

**Comment by fvpolpeta** [comment]
Hey -

Please try out version 3.1 RC1, which includes improved loupe:

https://horosproject.org/horos-content/Horos3.1.0RC1.dmg

Thanks

Fauze
