### ISSUE TITLE
horos v.3.0.0 

### ISSUE THREAD

**Issue by efnikos2000** [horosproject/horos#251]
I'm trying the v3.0.0 night version, with no scrolling issues but it's not loading the installed plugins, even those which are validated for Horos.

Thanks

**Comment by fvpolpeta** [comment]
Nothing was changed on the plugin loader. I have all the plugins (validated) installed and they load properly.

Can you launch Horos from terminal (/Applications/Horos.app/Contents/MacOS/Horos) send in my email the output you have?

Installed plugins dump some lines as Horos is being launched.

**Comment by aglv** [comment]
There may have been changes in the build flags, and there's a chance symbols aren't exported, so plugins may have problems loading. Let's just make sure that plugins work on our side before we release v3.
@efnikos2000 plugins seem to properly load, what does Horos log at launch? Please copy the relevant lines from the Console utility.

**Comment by fvpolpeta** [comment]
Yes - good tip. 

We plan to do RC evaluation period before making it official. 

I have the ones set as Horos plugin loading and working. 

Alessandro - 

Have you faced any linking failure among the plugin you may use or know someone is using?

**Comment by horosproject** [comment]
Hi -

By the logs you sent me, I see you are using Build 20180113.

Please, try this build:

https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180122.app.zip <https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180122.app.zip>

Plugins should be loading gracefully on this one.

Let me know your results.

Fauze

**Comment by efnikos2000** [comment]
hi again, from the link that you send me I have downloaded the zip file and instal ed but with the same problem regarding the plug ins. I started the application from the terminal and I noticed the version number ends in 113 and not 122


> 26 Ιαν 2018, 13:28, ο χρήστης «The Horos Project <notifications@github.com>» έγραψε:
> 
> Hi -
> 
> By the logs you sent me, I see you are using Build 20180113.
> 
> Please, try this build:
> 
> https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180122.app.zip <https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180122.app.zip>
> 
> Plugins should be loading gracefully on this one.
> 
> Let me know your results.
> 
> Fauze
>

**Comment by fvpolpeta** [comment]
Thanks.

I will be reviewing that and returning to you. 

I can get the plugins to work here without any trick. 

We talk

**Comment by efnikos2000** [comment]
terminal 

Last login: Fri Jan 26 15:06:42 on ttys000
Nikoss-MacBook-Pro:~ nikos$ /Applications/Horos.app/Contents/MacOS/Horos
2018-01-26 15:12:16.692 Horos[3516:546844] *-+-*-+-*-+-*-+-*-+-*-+-*-+-*-+-*-+-*-+-*-+-*-+-*-+-*-+-*-+-*-+-*-+-*
2018-01-26 15:12:16.692 Horos[3516:546844] Number of processors: 4 / 4
2018-01-26 15:12:16.692 Horos[3516:546844] Number of screens: 1
2018-01-26 15:12:16.692 Horos[3516:546844] Main screen backingScaleFactor: 1.000000
2018-01-26 15:12:16.692 Horos[3516:546844] Horos version: 20180113 - 3.0.0 - 64-bit
2018-01-26 15:12:16.692 Horos[3516:546844] OpenJPEG 2.3.0
2018-01-26 15:12:16.692 Horos[3516:546844] Localization: en.lproj
2018-01-26 15:12:16.711 Horos[3516:546844] |||||||||||||||||| Plugins loading START ||||||||||||||||||
2018-01-26 15:12:16.711 Horos[3516:546844] |||||||||||||||||| Plugins loading END ||||||||||||||||||
2018-01-26 15:12:16.714 Horos[3516:546860] start DNSResolve
2018-01-26 15:12:16.759 Horos[3516:546844] Graphics: Intel HD Graphics, 288MB
CoreData: error:  Failed to load model as no file exists at path '/Volumes/1TB/nikos/Library/Application Support/Horos/WebUsers.momd'
CoreData: error:  Failed to load keyed archive model at path '/Volumes/1TB/nikos/Library/Application Support/Horos/WebUsers.momd'
CoreData: error:  Failed to load NSManagedObjectModel with URL 'file:///Volumes/1TB/nikos/Library/Application%20Support/Horos/WebUsers.momd'
CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///Volumes/1TB/nikos/Library/Application%20Support/Horos/WebUsers.sql options:{
    NSInferMappingModelAutomaticallyOption = 1;
    NSMigratePersistentStoresAutomaticallyOption = 1;
} ... returned error Error Domain=NSCocoaErrorDomain Code=512 "The file couldn’t be saved." UserInfo={reason=Failed to create file; code = 2} with userInfo dictionary {
    reason = "Failed to create file; code = 2";
}
2018-01-26 15:12:16.928 Horos[3516:546844] Error: [N2ManagedDatabase contextAtPath:] Error Domain=NSCocoaErrorDomain Code=512 "The file couldn’t be saved." UserInfo={reason=Failed to create file; code = 2}
CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///Volumes/1TB/nikos/Library/Application%20Support/Horos/WebUsers.sql options:{
    NSInferMappingModelAutomaticallyOption = 1;
    NSMigratePersistentStoresAutomaticallyOption = 1;
} ... returned error Error Domain=NSCocoaErrorDomain Code=512 "The file couldn’t be saved." UserInfo={reason=Failed to create file; code = 2} with userInfo dictionary {
    reason = "Failed to create file; code = 2";
}
CoreData: error: Illegal attempt to save to a file that was never opened.  "This NSPersistentStoreCoordinator has no persistent stores (unknown).  It cannot perform a save operation.".  Last recorded error = Error Domain=NSCocoaErrorDomain Code=512 "The file “WebUsers.sql” couldn’t be saved in the folder “Horos”." UserInfo={NSFilePath=/Volumes/1TB/nikos/Library/Application Support/Horos/WebUsers.sql} / {
    NSFilePath = "/Volumes/1TB/nikos/Library/Application Support/Horos/WebUsers.sql";
}

2018-01-26 15:12:20.210 Horos[3516:546844] searchDICOMBonjour - searchForServicesOfType : _dicom._tcp
2018-01-26 15:12:20.211 Horos[3516:546844] Start bonjour DICOM search
2018-01-26 15:12:21.106 Horos[3516:546844] restartSTORESCP
2018-01-26 15:12:21.107 Horos[3516:547058] --- DICOMConnectionTimeout: 10
2018-01-26 15:12:21.112 Horos[3516:546844] Horos Bonjour net service did stop
2018-01-26 15:12:21.740 Horos[3516:546860] nikoss-macbook-pro.local
2018-01-26 15:12:21.740 Horos[3516:546860] Nikoss-MacBook-Pro.local
2018-01-26 15:12:21.741 Horos[3516:546860] localhost
2018-01-26 15:12:21.741 Horos[3516:546860] end DNSResolve
2018-01-26 15:12:22.636 Horos[3516:546844] Unicode test: مرحبا - 你好 - שלום
2018-01-26 15:12:26.107 Horos[3516:546844] startDICOMBonjour
2018-01-26 15:12:27.065 Horos[3516:546844] Find Service: <NSNetService 0x7faabd67ce10> local. _dicom._tcp. horos-mbp -1
2018-01-26 15:12:27.096 Horos[3516:546844] Remove Service: <NSNetService 0x7faabd67ce10> local. _dicom._tcp. horos-mbp 11112






















> 24 Ιαν 2018, 20:36, ο χρήστης «Fauze Polpeta <notifications@github.com>» έγραψε:
> 
> Nothing was changed on the plugin loader. I have all the plugins (validated) installed and they load properly.
> 
> Can you launch Horos from terminal (/Applications/Horos.app/Contents/MacOS/Horos) send in my email the output you have?
> 
> Installed plugins dump some lines as Horos is being launched.
> 
>

**Comment by fvpolpeta** [comment]
The problem is detected, it’s related to the refactoring of the framework naming conventions in the new building.

Working on that.

Fauze

**Comment by efnikos2000** [comment]
Ok, thank you


> 26 Ιαν 2018, 17:48, ο χρήστης «Fauze Polpeta <notifications@github.com>» έγραψε:
> 
> The problem is detected, it’s related to the refactoring of the framework naming conventions in the new building.
> 
> Working on that.
> 
> Fauze
>

**Comment by fvpolpeta** [comment]
Just to close the loop.

The build below keeps the legacy frameworks working with plugins, but due the fact some plugins may rely on library versions that now differ from the updated ones in the new building system, it’s not guaranteed that all the plugins will launch or execute as expected. Instability is also possible.

https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180128.app.zip <https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180128.app.zip>

We will be working to rebuild the plugins for Horos 3.0.0.

Please, advise on which plugins you use in your daily practice.

Thanks for using Horos.

Fauze

**Comment by efnikos2000** [comment]
Hi, I’ m using the ADC map, UMM diffusion, invert data, jpeg to dicom and resample data

Thanks for the prompt support

> 29 Ιαν 2018, 18:57, ο χρήστης «Fauze Polpeta <notifications@github.com>» έγραψε:
> 
> Just to close the loop.
> 
> The build below keeps the legacy frameworks working with plugins, but due the fact some plugins may rely on library versions that now differ from the updated ones in the new building system, it’s not guaranteed that all the plugins will launch or execute as expected. Instability is also possible.
> 
> https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180128.app.zip <https://www.horosproject.org/wp-content/uploads/nightly/Horos3.0.0Nightly20180128.app.zip>
> 
> We will be working to rebuild the plugins for Horos 3.0.0.
> 
> Please, advise on which plugins you use in your daily practice.
> 
> Thanks for using Horos.
> 
> Fauze
> 
>
