### ISSUE TITLE
building on OS10.13, xcode9.2

### ISSUE THREAD

**Issue by galenreed** [horosproject/horos#255]
Hello, 
I'm wondering if you know which settings to change to allow building on the latest mac OS/xcode versions. During horos compilation, I get the error:
No architectures to compile for (ARCHS=x86_64, VALID_ARCHS=i386).
Thanks immensely for your help, 
cheers!
galen

<img width="1209" alt="screen shot 2018-01-30 at 3 45 14 pm" src="https://user-images.githubusercontent.com/28761789/35593154-c2715666-05d4-11e8-8d06-1f120b6b45b2.png">

**Comment by aglv** [comment]
That's odd, Horos compiles on my 10.13 Xcode 9.2 setup. Did you change anything from the cloned Horos repository?

**Comment by galenreed** [comment]
Thanks, yep, I applied some suggested Xcode changes that messed up the build settings. 

Starting from scratch, I still get a build error related to missing cmake. It doesn't find when building horos, but when running the same command on terminal, it finds cmake in the macports install directory. Just wondering if you've seen this or happen to know a simple fix. Thanks for your help, Alessanrdo!
cheers
 

~/code/horos$ command -v cmake
/opt/local/bin/cmake


<img width="759" alt="screen shot 2018-01-31 at 3 33 28 pm" src="https://user-images.githubusercontent.com/28761789/35648724-48ebbf84-069c-11e8-9c63-f5eb42acd71c.png">

**Comment by fvpolpeta** [comment]
Below general instructions shared in other thread.

=> Close XCode

=> Remove Horos source code you checked out previously

=> Install newest XCode version (Don’t use betas, as we don’t use that too)

=> Install brew macos package manager (https://brew.sh/ <https://brew.sh/>)

=> Using command line terminal, use brew to install pkg-config: “brew install pkg-config”

=> Using command line terminal, use brew to install cmake: “brew install cmake” (you can install CMake downloaded from Kitware too)

(pkg-config and cmake are dependencies in the new build system)

=> Do a clean checkout of Horos via command line: git clone <horos git repository uri>

=> Open the Horos project with XCode

=> Go build

**Comment by galenreed** [comment]
@fvpolpeta @aglv works great, thank you for your support!!
cheers
galen

**Comment by aglv** [comment]
@fvpolpeta do you know which parts of the build system require pkg-config?

**Comment by galenreed** [comment]
@aglv @fvpolpeta do you have similar instructions for building plugins? for example the helloworld plugin.

**Comment by fvpolpeta** [comment]
I don’t have it right now, but as we go out with the Release Candidates of version 3.0 we will be rebuilding the plugins, that will incur on reviewing and create some instruction on how to do it.

The 3.0 RC will start to be rolled out next week.

Regards

Fauze
