### ISSUE TITLE
horos v3.0.0 - preferences/locations - WADO crasches

### ISSUE THREAD

**Issue by mcConti** [horosproject/horos#271]
When trying to change the WADO settings in "preferences / locations", Horos suddenly quits.
Horos 3.0.0 - 20180209

Horos 3.0.0 - 20180113 - the same problem

Horos 2.3.0 - 20171112 - no problem, this works ok  !!!

*********************************

Process:               Horos [809]
Path:                  /Applications/Horos.app/Contents/MacOS/Horos
Identifier:            org.horosproject.horos
Version:               3.0.0 (20180209)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Horos [809]
User ID:               

Date/Time:             2018-02-15 17:18:48.393 +0100
OS Version:            Mac OS X 10.13.1 (17B48)
Report Version:        12
Anonymous UUID:     

Time Awake Since Boot: 5200 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000ff00000018
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0xff00000018:
    MALLOC_LARGE           0000000143997000-0000000143c6f000 [ 2912K] rw-/rwx SM=PRV  
--> 
    MALLOC_NANO            0000600000000000-0000600001600000 [ 22.0M] rw-/rwx SM=PRV  

Application Specific Information:
objc_msgSend() selector name: _wrapsCarbonWindow
Performing @selector(editWADO:) from sender NSMenuItem 0x6080004a5ee0

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff6df24e9d objc_msgSend + 29
1   com.apple.AppKit              	0x00007fff44deb938 -[NSApplication beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:] + 245
2   Horos                         	0x000000010acddefb -[OSILocationsPreferencePanePref editWADO:] + 411
3   com.apple.AppKit              	0x00007fff452f2a7a -[NSApplication(NSResponder) sendAction:to:from:] + 312
4   com.apple.AppKit              	0x00007fff44d8843f -[NSMenuItem _corePerformAction] + 323
5   com.apple.AppKit              	0x00007fff44d881c7 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
6   com.apple.AppKit              	0x00007fff44e0dd9a -[NSMenu performActionForItemAtIndex:] + 133
7   com.apple.AppKit              	0x00007fff44e0dd05 -[NSMenu _internalPerformActionForItemAtIndex:] + 94
8   com.apple.AppKit              	0x00007fff44e0db35 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 106
9   com.apple.AppKit              	0x00007fff44cd45a2 NSSLMMenuEventHandler + 882
10  com.apple.HIToolbox           	0x00007fff46837284 DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1541
11  com.apple.HIToolbox           	0x00007fff468365cd SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 374
12  com.apple.HIToolbox           	0x00007fff4684b8d1 SendEventToEventTarget + 39
13  com.apple.HIToolbox           	0x00007fff46894e09 SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**) + 411
14  com.apple.HIToolbox           	0x00007fff468bdd3e SendMenuCommandWithContextAndModifiers + 49
15  com.apple.HIToolbox           	0x00007fff468bdcfa SendMenuItemSelectedEvent + 188
16  com.apple.HIToolbox           	0x00007fff468bdbd4 FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*) + 96
17  com.apple.HIToolbox           	0x00007fff469d621c PopUpMenuSelectCore(MenuData*, Point, double, Point, unsigned short, unsigned int, unsigned int, Rect const*, unsigned short, unsigned int, Rect const*, Rect const*, __CFDictionary const*, __CFString const*, OpaqueMenuRef**, unsigned short*) + 1662
18  com.apple.HIToolbox           	0x00007fff469d5697 _HandlePopUpMenuSelection8(OpaqueMenuRef*, OpaqueEventRef*, unsigned int, Point, unsigned short, unsigned int, unsigned int, Rect const*, unsigned short, Rect const*, Rect const*, __CFDictionary const*, __CFString const*, OpaqueMenuRef**, unsigned short*) + 409
19  com.apple.HIToolbox           	0x00007fff4689de3c _HandlePopUpMenuSelectionWithDictionary + 268
20  com.apple.AppKit              	0x00007fff44e048ca _NSSLMPopUpCarbonMenu3 + 5632
21  com.apple.AppKit              	0x00007fff44e03224 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 439
22  com.apple.AppKit              	0x00007fff44e73338 -[NSPopUpButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 570
23  com.apple.AppKit              	0x00007fff44e69089 -[NSTableView _tryCellBasedMouseDown:atRow:column:withView:] + 1818
24  com.apple.AppKit              	0x00007fff44e0ae51 -[NSTableView mouseDown:] + 5276
25  com.apple.AppKit              	0x00007fff45491a01 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5891
26  com.apple.AppKit              	0x00007fff4548e658 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2359
27  com.apple.AppKit              	0x00007fff4548d904 -[NSWindow(NSEventRouting) sendEvent:] + 497
28  com.apple.AppKit              	0x00007fff452ee937 -[NSApplication(NSEvent) sendEvent:] + 307
29  com.apple.AppKit              	0x00007fff44b50861 -[NSApplication run] + 812
30  com.apple.AppKit              	0x00007fff44b1f9d2 NSApplicationMain + 804
31  libdyld.dylib                 	0x00007fff6eb21145 start + 1

Thread 1:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff6ec71142 __select + 10
1   com.apple.CoreFoundation      	0x00007fff4757a63b __CFSocketManager + 635
2   libsystem_pthread.dylib       	0x00007fff6edab6c1 _pthread_body + 340
3   libsystem_pthread.dylib       	0x00007fff6edab56d _pthread_start + 377
4   libsystem_pthread.dylib       	0x00007fff6edaac5d thread_start + 13

Thread 2:: DICOM Store-SCP
0   libsystem_kernel.dylib        	0x00007fff6ec71142 __select + 10
1   Horos                         	0x000000010adb2c6a ASC_associationWaiting(T_ASC_Network*, int) + 138
2   Horos                         	0x000000010aae45d3 DcmQueryRetrieveSCP::waitForAssociation(T_ASC_Network*) + 99
3   Horos                         	0x000000010aaca956 -[DCMTKQueryRetrieveSCP run] + 2438
4   Horos                         	0x000000010a86de57 -[AppController startSTORESCP:] + 519
5   com.apple.Foundation          	0x00007fff495fd6d8 __NSThread__start__ + 1197
6   libsystem_pthread.dylib       	0x00007fff6edab6c1 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff6edab56d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff6edaac5d thread_start + 13

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6ec67e76 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6ec67390 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff475405d5 __CFRunLoopServiceMachPort + 341
3   com.apple.CoreFoundation      	0x00007fff4753f927 __CFRunLoopRun + 1783
4   com.apple.CoreFoundation      	0x00007fff4753efa3 CFRunLoopRunSpecific + 483
5   com.apple.AppKit              	0x00007fff44c992d1 _NSEventThread + 184
6   libsystem_pthread.dylib       	0x00007fff6edab6c1 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff6edab56d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff6edaac5d thread_start + 13

Thread 4:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	0x00007fff6ec67e76 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6ec67390 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff475405d5 __CFRunLoopServiceMachPort + 341
3   com.apple.CoreFoundation      	0x00007fff4753f927 __CFRunLoopRun + 1783
4   com.apple.CoreFoundation      	0x00007fff4753efa3 CFRunLoopRunSpecific + 483
5   com.apple.CFNetwork           	0x00007fff464b7662 +[NSURLConnection(Loader) _resourceLoadLoop:] + 357
6   com.apple.Foundation          	0x00007fff495fd6d8 __NSThread__start__ + 1197
7   libsystem_pthread.dylib       	0x00007fff6edab6c1 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff6edab56d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff6edaac5d thread_start + 13

Thread 5:: DCMTK Network release variables
0   libsystem_kernel.dylib        	0x00007fff6ec711d2 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff6ebec754 nanosleep + 199
2   com.apple.Foundation          	0x00007fff4969da37 +[NSThread sleepForTimeInterval:] + 156
3   Horos                         	0x000000010aad28f6 +[DCMTKQueryNode releaseNetworkVariables] + 182
4   com.apple.Foundation          	0x00007fff495fd6d8 __NSThread__start__ + 1197
5   libsystem_pthread.dylib       	0x00007fff6edab6c1 _pthread_body + 340
6   libsystem_pthread.dylib       	0x00007fff6edab56d _pthread_start + 377
7   libsystem_pthread.dylib       	0x00007fff6edaac5d thread_start + 13

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff6edaac40 start_wqthread + 0
1   ???                           	0x0002000200020000 0 + 562958543486976

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff6edaac40 start_wqthread + 0
1   ???                           	0x0000000000000001 0 + 1

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff6ec716da __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff6edab26f _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff6edaac4d start_wqthread + 13

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff6edaac40 start_wqthread + 0
1   ???                           	0x000000000001925b 0 + 103003

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000060c0007e2100  rcx: 0x000060c0007e2101  rdx: 0x000060c0001f8300
  rdi: 0x000060c0001f8300  rsi: 0x00007fff457f96fc  rbp: 0x00007ffee53a4e70  rsp: 0x00007ffee53a4e18
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x000000ff00000000  r11: 0x00007fff457f96fc
  r12: 0x000060c0001f8300  r13: 0x000060800010c9f0  r14: 0x00007fff457f6151  r15: 0x000060800010c9f0
  rip: 0x00007fff6df24e9d  rfl: 0x0000000000010206  cr2: 0x000000ff00000018
  
Logical CPU:     1
Error Code:      0x00000004
Trap Number:     14

**Comment by fvpolpeta** [comment]
Hi -

Please, evaluate if the problem persists on Horos 3.0.0 RC2, which was released today.

Let me know your results.

Thanks for reporting

Fauze

**Comment by mcConti** [comment]
ok, but how can I get Horos 3.0.0 RC2?

**Comment by fvpolpeta** [comment]
The 3.0.0 RC1 will notify you about the update. Alternatively you can go to the project website and download it.

**Comment by mcConti** [comment]
WADO setting works. Nice
