### ISSUE TITLE
Horos 3.0 hard crashes on trying to add or edit a destination for Routing

### ISSUE THREAD

**Issue by howardm** [horosproject/horos#272]
Hi,

As the title states. 

Here are the associated Crash Reports: https://www.dropbox.com/sh/6pyxi98lo00juz3/AADD9KH_N6jbddeOic5M18dLa?dl=0

The folder also has a screenshot showing the error message I received when prompted to send feedback using the Horos feedback reporting module.

Howard

**Comment by fvpolpeta** [comment]
Hi -

This has been fixed in the RC2 of Horos 3.0.0. Released today.

Please, let me know your results.

Thanks for reporting

Fauze

**Comment by howardm** [comment]
Great!  It works now.

Thanks.

Howard
