### ISSUE TITLE
"Bad ZIP file" error downloading plugins

### ISSUE THREAD

**Issue by jacopHoros** [horosproject/horos#278]
I get the same error downloading any of the available plugins. Can't install any.

OS High Sierra

**Comment by fvpolpeta** [comment]
Hi -

Thanks for report this.

Please, restart Horos, go to the Plugin Manager and confirm it's now working again.

Regards

Fauze

**Comment by jacopHoros** [comment]
Now the plugin is installed and apparently working, but when I open de JPEG with the plugin, it doesn’t appear in the data base afterwords.

I have the same problem if I try to import the JPEG directly: just nothing happens, no image goes to data base. I thought I could bypass the problem using the plugin JPEG to DICOM… but it still doesn’t work. Can you help me?

jacopo
