### ISSUE TITLE
No Updates checks: "no internet connection??"

### ISSUE THREAD

**Issue by jacopHoros** [horosproject/horos#281]
If I check for new updates, error always pops up "no internet connection". Obviously, THERE IS normal high-speed internet connection...

**Comment by yehoudin** [comment]
In Horos 2.2.0, "Check for updates" will respond that Horos would be up to date, however 2.4.0 was already rolled out....

**Comment by fvpolpeta** [comment]
Hi -

Thanks for reporting this. This was caused by a permission issue in our new website. 

It's fixed now. Please, check.

Best Regards

Fauze
