### ISSUE TITLE
10.11+ version not working on 10.11

### ISSUE THREAD

**Issue by jjfPCSI1** [horosproject/horos#282]
Hello,

I tried to install the Horos 2.2.0 (and 2K 2.0.2) version from the website (horosproject.org) which is marked to be runnable on macOS 10.11+, but when I try to open the App, it tells me that I need macOS 10.12 at least to make it work.

Is there a workaround or is it a typo on the website ?

Thanks,

JJ

**Comment by tessus** [comment]
I've compiled 2.2.0 for 10.11 last year. You can grab it here:

https://evermeet.cx/pub/macosx/Horos/Horos-2.2.0.zip

Update: Yes, it seems to be a typo on the web site.

**Comment by jjfPCSI1** [comment]
Thanks a lot, it's working!

**Comment by horosproject** [comment]
Hi -

We have regularized the minimum versions of our binaries. 

If you go to horosproject.org <http://horosproject.org/> you will find the original binaries for 10.11+

Thanks for reporting this.

Fauze
