### ISSUE TITLE
Building fails on 10.11.6

### ISSUE THREAD

**Issue by jjfPCSI1** [horosproject/horos#283]
Hello,

I tried to build Horos from the terminal typing `make` in the terminal from the root directory of the project. It builds a lot of things but ends up with the error

<pre>
** BUILD FAILED **

The following build commands failed:
	CompileC build/Horos.build/Release/Horos.build/Objects-normal/x86_64/AppController.o Horos/Sources/AppController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [Horos] Error 65
</pre>

In case it could be helpful, I attach the compilation output.
[error.txt](https://github.com/horosproject/horos/files/1763453/error.txt)

Any idea on what could be the issue? 

Thanks,

JJ

**Comment by tessus** [comment]
The current source tree requires Xcode 9.2. You are using 8.2.1 (8C1002).

You have to checkout the commit point for version 2.2.0. I believe you should also be able to compile 2.4.0 with your version of Xcode.
