### ISSUE TITLE
Horos and iCloud sync dialog/process

### ISSUE THREAD

**Issue by howardm** [horosproject/horos#284]
Hi,

Upon installation, Horos states (in a dialog box) that it has detected that I'm synced to iCloud, with the associated offer of establishing a Local (.nosync) Database.

That is a false-positive detection:  I have _not_ synced my Desktop/Documents folders to iCloud.

I suggest you check the relevant installation code.

Cheers,

Howard

**Comment by fvpolpeta** [comment]
Thanks Howard. I will be contacting you in private to proceed with an investigation.

In principle, I can't replicate this.

Fauze

**Comment by fvpolpeta** [comment]
This has been addressed. The iCloud Drive detection setting was modified to consider synchronisation of Documents & Desktop folders only. This is will available for evaluation in 3.0 RC#3 of Horos, which will take place in the next 15 days.
