### ISSUE TITLE
Horos crashing on DICOM import on 2 discs

### ISSUE THREAD

**Issue by jdbddsmd** [horosproject/horos#29]
I’m running the latest version of Horos.

I’ve received 2 discs of MRI’s on one patient. As soon as Horos starts to import the DICOM files, it crashes.

Both discs. Same thing. Y’all should have received the crash reports.

I can import these same discs into OsiriX MD with no problem.

What’s up with that?

Thanks,

Jim Bates, DDS, MD

**Comment by purview-craig** [comment]
Can you confirm the operating system you're running Horos 1.1.2 on? Is it El Capitan or something else?

**Comment by luflagoncalves** [comment]
I am having the exact time with el capitain. The predicament began for me after I installed Osirix lite in order to try to have discomfort images show under cover flow on finder

**Comment by jdbddsmd** [comment]
I'm running Yosemite 10.10.5, not El Capitan.

**Comment by fvpolpeta** [comment]
One potential cause for that problem has been found and it will addressed in the next release (1.1.3). Release will happen until Monday (16-Nov-2015). Your feedback is appreciated.

**Comment by jdbddsmd** [comment]
That's great news! I look forward to the new version on Monday!

**Comment by Mlopezrios** [comment]
Hi I'm having that problem any temporary solution so I can continue working

**Comment by fvpolpeta** [comment]
Right. Please, try the nightly build below and let us know how it goes on importing images from CD/DVDs

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

**Comment by Mlopezrios** [comment]
Hi, thanks for the help. but now the problem has changed, it doesn't crash anymore but the files on the dvd can't be seen.
you can just see the first series of the study.
Have to open Osirix, copy the files and then import to horos.

**Comment by fvpolpeta** [comment]
Hi Mr. Rios;

Thanks for the update and great it's not crashing anymore. Please, let me know if I did understand it right:
You are saying the studies imported from external media are being listed with only one series and they were supposed to have more?

**Comment by fvpolpeta** [comment]
Problem is addressed on Horos 1.1.3. Release date: 17-Nov-2015
