### ISSUE TITLE
"LOD" option in 3D MPR-curved viewer ?

### ISSUE THREAD

**Issue by mcConti** [horosproject/horos#319]
A) 
3D MPR-curved

Is it possible to add "LOD" option to 3D MPR-curved tab?

A big difference is caused by the change of "LOD". A little to the right (coarse) - no visible difference in picture quality but big difference in responsiveness. And for making 3D-curve responsiveness is imortant.

B)
And maybe a bug
"LOD" icon and "best" icon often disappear from the toolbar in 3D MPR viewer and I have to pull them back to the toolbar (customize toolbar).

**Comment by brizolara** [comment]
Hi,

A) Your feedback on this is appreciated. The 3D Curved MPR follows a very different pipeline than the 3D Volumetric/Surface/Endoscopy, as it renders plane images. So, the current LOD doesn't apply to the Curved MPR. A different LOD would have to be implemented for that...

B) I couldn't reproduce it here. If it keeps happening to you, please file an Issue reporting it, along with your MacOs and Horos versions

Tiago

**Comment by mcConti** [comment]
Hi
Thank you

A.  I mean to add LOD to the 3 windows on which we plot the curve - 2 top and left bottom. Rendered 3D curved plane images -> right bottom images "work" smoothly. 
Maybe if not all LOD, at least 2 or 3 degrees of quality, to improve responsiveness.

B. I don't know why "LOD" icon and "best" icons disappear from the toolbar.  It happens 1 or 2 in 10 Horos starts -> not MPR but full Horos. 3.0RC4, iMac27" late 2015, High Sierra.

**Comment by brizolara** [comment]
A. You are correct. It should be possible to apply a LOD in the Curved MPR views. I'll have a look at that!

B.  Thank you!

**Comment by brizolara** [comment]
Hi, mcConti,

This is fixed. Release 3.0.1. is on its way between today and tomorrow, with LOD available at the Curved MPR toolbar! 

And, I would like to ask you to open a different issue about the buttons disappearing from the 3d toolbar, just for the sake of organization.

Thanks!

**Comment by mcConti** [comment]
Thank you
I will check version 3.0.1 first. If the problem with buttons persists, then I will open new topic.
