### ISSUE TITLE
There are no Dentle3Dplugin in the Horos 3.0.0 ???

### ISSUE THREAD

**Issue by rhq2050** [horosproject/horos#329]
There are no Dentle3Dplugin in the Horos 3.0.0 ???

**Comment by fvpolpeta** [comment]
Unfortunately not yet. We are waiting for the author/maintainer to port it to 3.0.

Regards

Fauze

**Comment by rhq2050** [comment]
So...
It will be support, right?

Thanks for your reply.

**Comment by fvpolpeta** [comment]
Talked to maintainer…the answer is yes…no timeframe set as he needs to find time to make this happen. But, yes!

**Comment by Staslas** [comment]
really looking forward to this plugin. I guess as many.

**Comment by fvpolpeta** [comment]
The maintainer notified the Horos Team today about the release of a new version of Dental3DPlugin.

This version will be soon available in 3.0 and 2.4.1

Stay tuned. I will let you know from here.

Tks

**Comment by horosproject** [comment]
It’s live. Updated for 3.0.1 and 2.4.1

Best
