### ISSUE TITLE
Incorrect display of NM images

### ISSUE THREAD

**Issue by orr721** [horosproject/horos#33]
Hi there!

when I moved away from OsiriX I have noticed that NM images are not displayed correctly in Horos. They display as a top-down gradient from white to black. In the database preview they have an icon with question mark.

I have anonymized one scan and put it at https://dl.dropboxusercontent.com/u/310516/bone.dcm (528 kB). It should display an anterior whole body bone scan (you have to adjust the windowing a bit).The file displays correctly in ImageJ for example.

Is this already known? Can the developers look into this? Thank you very much for your outstanding work.

**Comment by fvpolpeta** [comment]
Thanks for reporting that. 

This issue is under investigation and will be fixed asap.

Best

**Comment by fvpolpeta** [comment]
Your images are now displayed properly in Horos. A nightly build of the App is available at:

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.app.zip

Please, report any issues you find.

Thanks again for using Horos.

Best Regards

**Comment by orr721** [comment]
Yes,  I can confirm that the NM images now display correctly.

Thank you very much, it is awesome that you can fix it so quickly.

Best regards..
