### ISSUE TITLE
Print failure message for Dicom jobs.

### ISSUE THREAD

**Issue by SandraFB** [horosproject/horos#338]
Hello, I couldn't print DICOM images since I update to Horos 3.0.1. Everything is ok, even the configuration of the printers but when i sent a job there's the message "Print failure- couldn't print images".

**Comment by SandraFB** [comment]
I installed the previous version of Horos and fixed the trouble.

**Comment by fvpolpeta** [comment]
Sandra -

Thanks for using Horos. Which previous version you installed to get it working?

Fauze

**Comment by SandraFB** [comment]
Version 2.2.0 👍
