### ISSUE TITLE
Home-made plugin not loading into Horos 1.1.4

### ISSUE THREAD

**Issue by giorgio-denunzio** [horosproject/horos#34]
Hi all.
I have been working on a Horos plugin for some months now. Till Horos 1.1.3 everything was ok, but now after upgrading to 1.1.4 the plugin does not load at Horos startup, and the following message is printed to the system console:

Plugins/ARIANItool.osirixplugin/Contents/MacOS/ARIANItool, 265): Library not loaded: @loader_path/../Frameworks/FeedbackReporter.framework/Versions/A/FeedbackReporter
     Referenced from: /Applications/Horos.app/Contents/Frameworks/HorosAPI.framework/Versions/A/HorosAPI
     Reason: image not found

I guess the error may have something to do with possible changes in HorosAPI.framework. For the sake of completeness, I do not remember where I took the framework from (I did it many months ago): I have just found a note where I wrote down that I had not taken it from the Horos Plugin Generator, I don't know if this fact can be related.
Any hint?
I can share the relevant part of the code if it can be useful.
Thanks
## Giorgio

Giorgio De Nunzio
University of Salento / INFN / ADAM (Advanced Data Analysis in Medicine) srl
Lecce - Italy

**Comment by fvpolpeta** [comment]
Dear Giorgio;

Thanks for using Horos and reporting this.

Your problem is under investigation and will be solved ASAP.

Best Regards

**Comment by fvpolpeta** [comment]
Hi Georgio;

In principle, the issue you reported is fixed. 

Please, download the following build of Horos, and let me now if your plugin is back to work. If so, I will  close the issue.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.app.zip

Regards

**Comment by giorgio-denunzio** [comment]
It works!
Great! Thank you very much!
Best regards
Giorgio

Il 01/12/2015 18:27, Fauze Polpeta ha scritto:

> Hi Georgio;
> 
> In principle, the issue you reported is fixed.
> 
> Please, download the following build of Horos, and let me now if your 
> plugin is back to work. If so, I will close the issue.
> 
> https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.app.zip
> 
> Regards
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/horosproject/horos/issues/34#issuecomment-161040145.

## 

Dr. Giorgio De Nunzio
Dipart. di Matematica e Fisica "Ennio De Giorgi", Univ. del Salento
INFN Sezione di Lecce
DReAM (Laboratorio Diffuso di Ricerca Interdisciplinare Applicata alla Medicina)
ADAM (Advanced Data Analysis in Medicine) srl
Lecce (Italy)
giorgio.denunzio@unisalento.it
giorgio.denunzio@adamgroup.it
tel +39 0832 297084-297051
fax +39 0832 297100
mobile +39 320 3829845

---

Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by fvpolpeta** [comment]
Fixed
