### ISSUE TITLE
cmake-error: horos-horos/CharLS" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by ustcpingzi** [horosproject/horos#343]
I have configured cmake, however Xcode is wrong with lacking of CMakeLists.txt when running Horos.xcodeproj. Why?

**Comment by brizolara** [comment]
Hi Ustcpingzi,

As I can remember, you've succeeded on building Horos.

Horos should work without problems in current Mac OS and XCode versions. I'm closing the issue, ok?

Thanks for using Horos!
