### ISSUE TITLE
Crash (EXC_BAD_ACCESS) when browsing remote database

### ISSUE THREAD

**Issue by DD-P** [horosproject/horos#348]
(Horos 3.0.1 client reading Horos 3.0.1 server)

- Crashes consistently
- On main thread
- E.g. in -[DCMPix loadDICOMDCMFramework]
- Referencing `srcFile` and `cachedDCMFrameworkFiles`

I've tried placing @synchronized around the code without effect.  It's not obvious to me what the problem is, however, the following (abbreviated) log entry appears before the crash.

```
Failed to load model as no file exists at path '$TEMP/Horos Data/Database.momd'
CoreData: error:  Failed to load model as no file exists at path '$TEMP/Horos Data/Database.momd'
```
This is followed by `Failed to load keyed archive model` log entries.

In the relevant temporary folder `Database.momd` exists, with `OsiriXDB_DataModel.mom/omo` and `VersionInfo.plist` files, which I believe are correct.

**Comment by aglv** [comment]
Please let us know is the next release fixes this for you.

**Comment by DD-P** [comment]
Version 3.3.5 does fix the issue, thank you very much Alessandro.
