### ISSUE TITLE
White square slice errors

### ISSUE THREAD

**Issue by nwdobbs** [horosproject/horos#38]
Hi there,
I'm encountering an issue on Horos which has developed acutely this evening.  I have a CT head stack which was working perfectly earlier today.  However, looking at it this evening, a number of white square lines have been introduced which cause errors when performing reconstructions.

When scrolling down the slice number goes for example from Z: -475.92mm with a normal slice, and on the next slice skips to z: -451.43.  The next slice would be the one that should have been in the white squre.  However, this is unreliably demonstratable, and seemingly not related to data corruption; when copying the same file into a new folder and loading, this slice loads fine, but similar errors occur in other locations.  Also, when going back to the same scan, in the same location, the slice error moves.  Initially I thought it was solely related to tilted gantry acquisitions or a single dicom folder, however loading scans from a non tiltable gantry gives the same errors.

Given that all scans behaved normally on both the work system, and also on my own laptop earlier, I feel that this is unlikely related to my hardware.  However, I am perplexed as to the root cause.

System info:
MacBook Pro (Retina, 13-inch, Early 2015)
3.1 GHz Intel Core i7

16 GB 1867 MHz DDR3

Intel Iris Graphics 6100 1536 MB

Latest version of Horos as of 10th December 2015

Many thanks for any insight,

Nick
![ct1](https://cloud.githubusercontent.com/assets/16246748/11728783/b9d103a8-9f83-11e5-92be-8e9dcc9642d8.jpg)
![ct2](https://cloud.githubusercontent.com/assets/16246748/11728785/bb4a9a14-9f83-11e5-9a4c-6638068054f0.jpg)
![ct3](https://cloud.githubusercontent.com/assets/16246748/11728787/bcd0c7a0-9f83-11e5-9f43-22e1d9077c2d.jpg)

**Comment by nwdobbs** [comment]
I have repeated the whole process (extraction from main computer, anonymisation, and transfer to the teaching database.  Initially once again the axial stacks were without problem in Horos, suggesting that the data is not corrupt.   However, after using the horos reconstruction to view in sagittal plane, the white squares returned, in different places.

**Comment by nwdobbs** [comment]
I have further investigated this.
Taking the initial dataset (pre Horos) and putting it into Osirix lite is normal - this allows reconstruction into the different planes without error

Taking the post Horos reslicing data and putting it into Osirix lite - the squares shown above are there in the same place.

Therefore it appears that during the reslicing process for some reason Horos is putting these blank white square slides in for reasons unclear to me.  Any help would be appreciated.  I'll look over the settings with a fine eye, but am not sure what I'm looking for or if it's an issue which is not resolvable by settings.

Thanks,
Nick

**Comment by nwdobbs** [comment]
The issue is resolved after putting the data back in fresh again.  I made two changes leading to the fix and I am unsure which was responsible.

1) Installed osirix to test before moving back to Horos.
2) Copied some of the viewer and 3d preferences from osirix to Horos - unfortunately I wasn't paying attention to what I changed, was just tick boxing.

While this is resolved, any comments on what may have caused it would be greatly appreciated as it still perplexes me what happened.

Thanks - and thanks for the amazing work with Horos!

**Comment by nwdobbs** [comment]
Am even more perplexed now - in the time it took to write the above article I went back to Horos, and the white squares are back.  No idea what is going on.

**Comment by Staslas** [comment]
same bug!! very annoying! when appearing i can't use curved MPR anymore. 
<img width="1268" alt="2016-03-15 16 27 45" src="https://cloud.githubusercontent.com/assets/17851883/13779612/e8cdca8a-eacc-11e5-8a33-edcb03b05078.png"> in MPR 
<img width="451" alt="2016-03-15 16 28 02" src="https://cloud.githubusercontent.com/assets/17851883/13779636/0d27f43c-eacd-11e5-8bcf-54aaa40d484c.png">

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze

**Comment by nwdobbs** [comment]
Hi there, sorry for the slow reply I've been away then interview prepping
etc.  Will try this out over the weekend and get you some feedback.  Thanks
very much for looking into it, its hugely appreciated.

Cheers,
Nick

**Comment by fvpolpeta** [comment]
No problem, you are welcome.

Try this:

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos2.0.0RC3.dmg

It's the latest Release Candidate build which will be released next days.

BR
