### ISSUE TITLE
Is there an URI for calling horos from other applications like horos:// ?

### ISSUE THREAD

**Issue by volkans80** [horosproject/horos#389]
Hi,

Is there an URI for calling horos from other applications like horos:// ?
I can't find any documentation.

For example we can call osirix and open a study with this URI,
osirix://?methodName=DisplayStudy&PatientID=111111&StudyInstanceUID=1.2.3.4.5.6.7.8.9

Thanks,

**Comment by fvpolpeta** [comment]
horos:// works for Horos, but it seems OsiriX is also enabled to capture horos://, which means some conflict around which one will be preferred may occur in case you have both installed in your mac.

**Comment by volkans80** [comment]
Thanks,
