### ISSUE TITLE
Selecting "Export All Images of the series" only exports one image.

### ISSUE THREAD

**Issue by colinbjohnson** [horosproject/horos#39]
# Steps to Reproduce
1. Open the Horos application.
2. Click the "Query" icon to bring up the query window.
3. Search for a Name/Patient Name - wait for the results to be returned.
4. Click twice on one of the returned patients to open the Patient.
5. Go to "File" menu and select "Export to JPEG" - the "Export to" window will appear.
6. Select "All images of the series" and press OK.
# Result
- only the "active" image will be exported.
# Expected Result
- all images in the selected series would be exported.

**Comment by fvpolpeta** [comment]
Hi;

Thanks for using Horos. 

Can't reproduce the problem you reported. In my system Horos export all expected JPEG files and then subsequently opens Preview.app with the first filed exported. Anyway, all files are exported.

If your are really experienced this problem, I request you to provide us with an anonymized image series.

BR
