### ISSUE TITLE
Blank Series Icon in Toolbar

### ISSUE THREAD

**Issue by ky-tech-guy** [horosproject/horos#4]
In the 2d viewer, the series icon on the toolbar does not show the series that has been selected.  It appears blank.  See the image below for details.  I have noticed that if you right click on the image, the series icon will show the correct image.  You can obtain the dataset.....at http://199.19.86.163:3333/main.  Search for alveolar proteinosis. 
![blankseriesontoolbar](https://cloud.githubusercontent.com/assets/10901615/6881756/836ec18e-d543-11e4-8f7c-0b45814cc205.jpg)

**Comment by fvpolpeta** [comment]
In principle, already fixed in the git repository. Next release will feature the correction for this glitch. Thanks for reporting.
