### ISSUE TITLE
I have CMake installed but it says this

### ISSUE THREAD

**Issue by rjustinragasa** [horosproject/horos#402]
+ '[' -e Makefile -a -f .cmakehash ']'
+ command -v cmake
+ echo 'error: building CharLS requires CMake. Please install CMake. Aborting.'
error: building CharLS requires CMake. Please install CMake. Aborting.
+ exit 1

**Comment by fvpolpeta** [comment]
Hi -

Did you follow the build instructions outlined here:

https://github.com/horosproject/horos

You must have cmake and pkgconfig installed.

You can install them using brew (https://brew.sh)

Fauze
