### ISSUE TITLE
strange order in WORD report files folder and MOJAVE

### ISSUE THREAD

**Issue by lmenegazzo** [horosproject/horos#408]
Since Mojave i`m having a strange behaviour in my REPORT files. They are not alphabetically ordered as in HIGH sierra,  already tried change sort attributes in WORD TEMPLATES folder in finder but nothing seems to work. In high sierra everything ok.
![screen shot 2018-10-09 at 22 34 56](https://user-images.githubusercontent.com/36492767/46708363-a8e82b00-cc14-11e8-8008-f5e250b79416.png)
<img width="638" alt="screen shot 2018-10-09 at 22 35 32" src="https://user-images.githubusercontent.com/36492767/46708368-ad144880-cc14-11e8-93e7-d7b89408bdbc.png">

Please help.

**Comment by JeanClaude2** [comment]
Hi @lmenegazzo, I think they changed the reporting function: it's now a cloud. You can buy it here:
https://horosproject.org/horos-reporting/

**Comment by lmenegazzo** [comment]
They did not change.
The same horos version runs well in high sierra.
Is a bug relate to Mojave.

**Comment by aglv** [comment]
My #412 addresses this problem. The templates weren't being sorted at all, they previously seemed to be sorted because of an undefined behavior that changed with Mojave.

**Comment by lmenegazzo** [comment]
Really thanks Alessandro!

**Comment by lmenegazzo** [comment]
issue closed in last version, thanks!
