### ISSUE TITLE
Horos: problem with color doppler

### ISSUE THREAD

**Issue by paoloprati** [horosproject/horos#41]
Sometimes, horos has problem with the color doppler images. I can find this problem in a lot of color clips and images.
![horos problem color doppler](https://cloud.githubusercontent.com/assets/16254323/11742387/d6b62f94-9fff-11e5-96f5-1b673f41f0c1.jpg)

**Comment by fvpolpeta** [comment]
Hi
Please, can you provide us with a anonymized series that causes the problem?
Thanks for using Horos.

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

To help you with colors, see:

https://github.com/horosproject/horos/issues/88

Best Regards

Fauze

**Comment by riversde** [comment]
I can confirm the doppler issue is fixed on the Nightly version.  Thanks a lot!!  Looking good 2.0,

Hope to see Q/R on multiple database locations..
