### ISSUE TITLE
Something is wrong with 3D.

### ISSUE THREAD

**Issue by Shalf13** [horosproject/horos#417]
Something is wrong with 3D. Incorrectly displayed when opening (enlarged, located in the upper left corner, the center is shifted when moving and rotating) after the last update. In version 3.2.2 everything was fine.

**Comment by fvpolpeta** [comment]
Hi -

The issue is confirmed. It doesn't happen with any studies. We are investigating.

Stand by

**Comment by Shalf13** [comment]
Additionally.
The problem appeared after updating on two different devices at the same time (iMac 2017 & MacBook pro 2013). Studies from different tomographs, but both produced by Toshiba. Returning to version 3.2.2 solves the problem.

**Comment by FabriceHx** [comment]
I have the same problem with the latest update. I suggest you to have a minimum of functional tests or clinical validation before releasing a new version... If you want to distribute a FDA certification, it will be mandatory or you could have major problems with the FDA.

**Comment by DokBill** [comment]
I have the same issue with the newest update. Very unfortunate for such a good program. Running on a MacBook Pro 2018. OS Mojave 10.14

**Comment by DokBill** [comment]
Update: I have gone back to the previous version & will wait for the patch to be launched.

**Comment by fvpolpeta** [comment]
Hi @DokBill , @Shalf13  -

Could you please try the build below. It's a release candidate for version 3.3.3 of Horos.

https://horosproject.org/horos-content/Horos3.3.3_RC1_20181109.dmg

Your collaboration is appreciated to confirm the 3D issue is resolved.

Thanks

**Comment by DokBill** [comment]
Thank you
That seems to have corrected the problem.
Well done.

Dr. W. Charlton
docbill@cogeco.ca
Ph (705) 646-8887
Fax (705) 646-8845

**Comment by fvpolpeta** [comment]
Solved in 3.3.3
