### ISSUE TITLE
Export DICOM files appears to have changed

### ISSUE THREAD

**Issue by matthiasschabel** [horosproject/horos#419]
In the past, when a study was exported from Horos, the study name and sequence names would be used as folders and files were exported with filenames IM-XXXX-YYYY.dcm. Now it appears to be simply exporting files without altering their names or organization. Unfortunately, this breaks code that used Horos to parse studies from various different vendors and put it into a consistent directory/file structure. Wondering what the rationale for the change is and, ideally, if it can either be reverted or the previous functionality restored elsewhere?

**Comment by fvpolpeta** [comment]
Hi Matthias -

Please, try the build below and let me know it solves your issue.

https://horosproject.org/horos-content/Horos3.3.3_Nightly20181106.dmg

Before doing an export go to Preferences=>Database=>File Management Box

Uncheck the "Use DICOMDIR structure when exporting to filesystem".

Let me know if it works

Fauze

**Comment by matthiasschabel** [comment]
Hi Fauze - works perfectly! Thanks so much for fixing this so quickly…

Best,

Matthias
