### ISSUE TITLE
Feature request: support multiple parallel databases

### ISSUE THREAD

**Issue by matthiasschabel** [horosproject/horos#420]
I am currently manually managing multiple Horos databases for various research projects via renaming of the Horos database folder in a script. It seems like this ought to be possible in a cleaner way by, e.g., just having a pulldown in the database preferences that allows you to select one of multiple databases stored in the Documents folder. Thoughts on how feasible this is?

**Comment by sorenchr2011** [comment]
Hi,
 I'm not sure I fully understand what you're after. You can switch between
databases by clicking in the "sources" panel. Isn't this doing what you are
after?

Soren

**Comment by matthiasschabel** [comment]
I don't know how to add an additional local database to the "Sources" panel. I see my main "Documents DB" and a couple of PACS servers that I use, but would like to add other local databases and switch between them. So it sounds like perhaps I'm just ignorant of the process?

**Comment by sorenchr2011** [comment]
try
File->New database folder

For unknow reasons this dialog does not let you create a new folder (that I
am aware of), but it will initialize a new DB in the folder you point to.
So I usually make a subfolder in Documents, or elsewhere for each database.
Eg Documents//Project1   Documents/Projects2 and you then add the new
databases to those subfolders.

Soren

**Comment by matthiasschabel** [comment]
That is super helpful. Thanks! Completely resolved my problem - I just wasn't quite getting the paradigm.
