### ISSUE TITLE
Horos 3.3.1 and 3.3.2 version 3D rendering issues

### ISSUE THREAD

**Issue by robcry** [horosproject/horos#424]
Hello all,
I have updated Horos to version 3.3.x, when I want to render a 3D volume or a 3D MIP the content of the window is blank, after using the cursor to rotate the image, the image is displayed but is not centred.
After rotating the images the content of the window become blank again.

**Comment by vishnuravilla** [comment]
i am also facing the same issue

**Comment by kristoffcornelis** [comment]
I have the same issue. Actually, I already had this once in a previous version, but by coincidence I had to by a new Mac... So in a complete new MacBook no more issues, until some days ago, it started again. I deleted "/Users//Library/Preferences/org.horosproject.horos.plist" but no success.
I'm not planning to by another Macbook for this...

**Comment by BenicioLima** [comment]
I have the same issue. Is it possible to download older versions of Horos?

**Comment by fvpolpeta** [comment]
Hi -

This has been addressed in version 3.3.3.

Proceed with download & installation and you will be good.

Fauze
