### ISSUE TITLE
display cross reference lines and 3d point not working 

### ISSUE THREAD

**Issue by fmmcradiology** [horosproject/horos#425]
display cross reference lines and 3d point not working  in horos 3.3.2, working well in old 2.4.1, kindly solve the issue

**Comment by JeanClaude2** [comment]
I have the same issue...
@aglv can you please fix this bug ? Thank you !

**Comment by amoors** [comment]
Likewise, also experiencing this issue with cross reference overlays no longer visible when viewing studies since upgrading from 2.4.1.
Have rolled back to 2.4.1 for now but would appreciate being able to use newer version with dicom ovelays intact.

**Comment by fvpolpeta** [comment]
Hi @fmmcradiology @JeanClaude2 

Please, let me know in which module/function the cross reference lines and 3D points are not working? (3D Volume, 3D MPR, 3D Curved MPR)

Thanks

**Comment by amoors** [comment]
@fvpolpeta In my case the lack of cross reference lines occurs when viewing any study with multiple series in different planes. I have ensured that "Display Cross Reference Lines" is enabled in "2D viewer > Annotations", but this makes no difference.

Multiple users in my organisation have noted this issue on various machines with a wide range of specs.

**Comment by ramru01** [comment]
I also have the same issues especially with MRI's. It is issue 377 on this blog.

**Comment by fmmcradiology** [comment]
> Hi @fmmcradiology @JeanClaude2
> 
> Please, let me know in which module/function the cross reference lines and 3D points are not working? (3D Volume, 3D MPR, 3D Curved MPR)
> 
> Thanks

2d or 3d no where it is working in versions after 2.4.1

**Comment by fvpolpeta** [comment]
Hi -

I can't replicate the problem. Reference lines and overlay are working as expected in my environment.

I'm using the build below:

https://horosproject.org/horos-content/Horos3.3.3_RC1_20181109.dmg

Is this happening to any study? Do you mind on sharing one anonymized that you can't use reference lines?

Thanks

**Comment by amoors** [comment]
Hi,

The issue happens with any MRI acquisition, I have tried the build provided with various users and machines, but this still does not display the cross reference lines - See images below:

Horos 2.4.1:
![horos 241](https://user-images.githubusercontent.com/44697981/48260193-7481ad80-e412-11e8-85e5-b40057721e8c.png)

Horos 3.3.3
![horos 333](https://user-images.githubusercontent.com/44697981/48260194-7481ad80-e412-11e8-8e8d-f2354b68bbff.png)


Please find an anonymised study with multiple planes at the following link: https://www.dropbox.com/s/qrhnvvrypqfzj4f/NO_NAME.zip?dl=0

Interestingly 3.3.3 also syncs all series when scrolling, rather than only syncing those in the same orientation.

Many thanks for your help!

**Comment by fvpolpeta** [comment]
Thanks for sharing. We will be investigating.

Fauze

**Comment by fvpolpeta** [comment]
Hi @amoors, @JeanClaude2,

Please check the build below and confirm reference lines are back.

https://horosproject.org/horos-content/Horos3.3.3_RC2_20181109.dmg

Let me know if it works.

Thanks

Fauze

**Comment by fvpolpeta** [comment]
@amoors 

With the following series:

https://www.dropbox.com/s/gfqor3ydxmlmli8/Anonymized.zip?dl=0

I have cross reference lines working as expected. I have to investigate a bit more why the lines doesn't work for your study. 

Any version you have it working in the past? That may help me to be quicker on resolution.

Fauze

**Comment by amoors** [comment]
@fvpolpeta Reference lines work in the new build with the study you provided, however do not work on the study I provided (nor any other MRIs).

Reference lines work up until version 3.0.1, after this release they no longer appear.

Many thanks.

**Comment by fvpolpeta** [comment]
Hi @amoors 

I tested the study on version 3.0.1. (https://horosproject.org/horos-content/Horos3.0.1.dmg)

Reference lines also don't work on it. I have other MRI studies where they work properly too.

The reason they don't work with your study is because there is a loss of spatial correlation between the series, which is necessary to render the reference lines.

We will continue to investigate. But the reference lines also don't work in other viewers I tried (OsiriX Lite and Radiant). It might be something related to your study.

Regards

Fauze

**Comment by amoors** [comment]
@fvpolpeta many thanks for looking into this.

If it is of help/interest, we also have a limited number of Machines which run OsiriX 9.0.2, which do display the cross reference lines correctly.

**Comment by fvpolpeta** [comment]
You're welcome.

I will double check OsiriX. Perhaps, I did not open right series of your study. Anyway, in Horos, by what I could see, it seems the spatial coordinates that defines the correlation between the series is getting corrupted (0 or infinite).

Fauze

**Comment by amoors** [comment]
How bizarre.

I have just tested viewing the study in a browser-based system (eUnity) as well, which does display the reference lines. I am happy to provide further anonymised studies if this would be of help.

**Comment by fvpolpeta** [comment]
By now, the one you provided is enough. For some of the series I got reference lines in OsiriX Lite 10.0.x

But please, confirm version 3.0.1 of Horos shows reference lines in your station.

It doesn't show in mine, what suggests me it's a problem that already existed.

Fauze

**Comment by amoors** [comment]
Reference lines definitely shown in 3.0.1, please see below:

![screenshot 2018-11-12 at 14 56 54](https://user-images.githubusercontent.com/44697981/48355150-44910f00-e68b-11e8-82ab-2f8287a76770.png)

**Comment by fvpolpeta** [comment]
Right. My bad, I probably selected wrong series.

With that in hands I'm able to inspect what has changed since 3.0.1

I let you know when I find something.

Thanks

**Comment by amoors** [comment]
Many thanks @fvpolpeta, much appreciated!

**Comment by fvpolpeta** [comment]
Hi all (@fmmcradiology @amoors @JeanClaude2)

Please, check the build below and let us now if the situation where you had issue with reference lines is solved:

https://horosproject.org/horos-content/Horos3.3.4_Nightly20181118.dmg

Let me know about 3D points too.

Thanks

Fauze

**Comment by amoors** [comment]
@fvpolpeta reference lines work beautifully, thank you so much for the quick fix - I will have many happy clinicians now!

![screenshot 2018-11-19 at 09 40 34](https://user-images.githubusercontent.com/44697981/48698551-456ff680-ebdf-11e8-91ad-4f73d216a56a.png)

**Comment by fvpolpeta** [comment]
Thanks for the support and feedback.
