### ISSUE TITLE
Links to Horos documentation or technical manual

### ISSUE THREAD

**Issue by TannerSorensen** [horosproject/horos#443]
I am interested in using Horos for an MRI study. I am looking for more information on the 3D multi-planar reconstruction (MPR) tool. Is there a technical manual for Horos or documentation of the 3D MPR tool?

**Comment by TannerSorensen** [comment]
I did some more searching around. Based on the what I read at the Horos Google Group (e.g., https://groups.google.com/forum/#!searchin/horos-project/documentation%7Csort:date/horos-project/Xm5-f-GoTTA/NClcgAsPCAAJ), it seems that a technical manual or documentation is in the process of being written, but is not yet finished.

**Comment by fievelk** [comment]
Hi, was there any development about this?

**Comment by tanner-sorensen** [comment]
Unfortunately, I doubt it. There hasn't been a commit to the default branch in over two years.
