### ISSUE TITLE
Crash Reporter Not Working

### ISSUE THREAD

**Issue by ky-tech-guy** [horosproject/horos#45]
The crash reporter feature does not appear to work in Horos 1.1.4. I have had Horos show the spinning wheel of death many times and had to force close it because the application was not responding. When I re-open it, no crash log is created. I am using a 2015 macbook pro w/ 8 gb ram.

**Comment by fvpolpeta** [comment]
Forcing Horos to quit doesn't mean you are causing a crash. We plan to add to Horos a feedback report system that will enable users to send us diagnostic data in order to have proper information to solve problems like yours.

Thanks for your help.
