### ISSUE TITLE
How do I get the cropping box coordinatrs

### ISSUE THREAD

**Issue by AboudFayad** [horosproject/horos#456]
I am making a plugin to get the cropping box coordinates from the 3D model generated in the 3D Volume Rendering window.

I tried to get the coordinates from the VRView in the 3D classes from the ​getCroppingBox method, but it is commented out in the code. Adding it again to my plugin, did not work and just created more problems with the libraries. I cannot uncommented or try to manipulate it, since it is commented in the release version.

**Comment by aglv** [comment]
It's commented out in the code, but the method body is visible. It calls +(BOOL)[VRView getCroppingBox:(double*)a :[self volume] :(vtkBoxWidget*)w]. 

You can easily call the same method from a plugin. just add a category to VRView with -(BOOL)MyPluginsGetCroppingBox:(double*)a { return [VRView getCroppingBox:a :volume :croppingBox]; } and call that.

**Comment by AboudFayad** [comment]
Thanks that worked.
