### ISSUE TITLE
Get access to the VRView 

### ISSUE THREAD

**Issue by AboudFayad** [horosproject/horos#457]
I am making a plugin that needs to access the VRView, I have found that I can use 
```mm
VRController *vrController = [viewerController openVRViewerForMode:@"VR"];
VRView * vrView = [vrController view];
```
but this does not give me the currently opened VR view.

**Comment by aglv** [comment]
VRControllers inherit from NSWindowController. You can iterate all currently open windows OR consider just the the current key window. Get its controller through window.windowController, check it with [window.windowController isKindOfClass:VRController.class] and access the view.

**Comment by AboudFayad** [comment]
Thank you so much, that did the trick :)
