### ISSUE TITLE
Using VTK 8 in a plugin

### ISSUE THREAD

**Issue by AboudFayad** [horosproject/horos#458]
I am trying to use VTK (VTK 8) in my plugin to load an obj/stl file, but I always get redefinition errors when using it with the OsirixAPI, since Osirix uses VTK 5.8 . Hence I tried to get VTK 5.8 on my macbook air (MacOS 10.14) but that gave so many compilation issues, and when ran I get missing ObjReader dylib linker. So I decided to use Horos since it uses VTK 8, but I am not sure how I can access the API after building it and adding it to my frameworks.

**Comment by aglv** [comment]
My suggestion is, avoid using the VTKs from the main binary. Different versions of Horos or OsiriX may link to different versions of VTK with different APIs. Nothing guarantees that the APIs you are using will be there at runtime.

Instead, build your own VTK generating static libraries, and link to those. The Horos xcodeproject includes a target that builds VTK from source. Look at [this](https://github.com/horosproject/horos/blob/horos/Horos/Scripts/VTK/CMake.sh) and [this](https://github.com/horosproject/horos/blob/horos/Horos/Scripts/VTK/Make.sh) script, and you should be able to build it on your side.

**Comment by AboudFayad** [comment]
I have already built VTK 8 from source using cmake, but the standard way and not in the same way it is done in the scripts you have linked, since I don't have much experience using makefiles. I did link the VTK 8 static libraries that are generated by the build, but they gave the redefinition errors when used with OsirixAPI. Is it because of the way I have built VTK 8?
