### ISSUE TITLE
Corruption of some frame images after "Merge Selected Studies"

### ISSUE THREAD

**Issue by PabloSau** [horosproject/horos#46]
Lately when I try to merge studies, e.g. basal vs delayed images, nearly all of the new series contain corrupted image data as shown in attached file.
![horoserror](https://cloud.githubusercontent.com/assets/16240012/11973340/10d5f418-a959-11e5-83e8-c82eb32913fa.jpg)

**Comment by fvpolpeta** [comment]
Hi;

Can you send us anonymized versionsof these series and instruct us on which series have you merged that lead to that issue.

Thanks in advance.

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze
