### ISSUE TITLE
3D MPR crashes Horos after OS 10.14.4 update yesterday

### ISSUE THREAD

**Issue by vkmcewen** [horosproject/horos#474]

**Comment by vkmcewen** [comment]
This is still happening, albeit sporadically. This is the details. I can paste more if necessary.
<img width="1130" alt="Screen Shot 2019-04-21 at 12 32 58 PM" src="https://user-images.githubusercontent.com/49315440/56472859-e33b4c00-6431-11e9-9248-48ff68d6c857.png">

**Comment by jensen0914** [comment]
Duplicate of #528.
