### ISSUE TITLE
Import failure

### ISSUE THREAD

**Issue by gs503** [horosproject/horos#476]
When importing dicoms, activity panel reads 'Adding Files', goes through copying, indexing and synchronisation, but then only one file (of 426) shows within the database; 

![Screen Shot 2019-04-09 at 09 32 41](https://user-images.githubusercontent.com/49404294/55785796-f6056680-5aaa-11e9-940c-c952d7e84686.jpg)

Any assistance is gratefully received. Thanks.

**Comment by sorenchr2011** [comment]
Were they generated directly by a modality or subject to some downstream
de-identification process?  If de-identification is involved, then read in
one file, and check the SOPInstanceUID of that file. Erase it, and read in
another file. Ensure that the UIDs differ. If they don't then that is the
issue - your images all have the same UID.I'd start with that check!

Soren

**Comment by gs503** [comment]
Very helpful- thanks Soren!
