### ISSUE TITLE
Export ROI Plugin issue

### ISSUE THREAD

**Issue by gs503** [horosproject/horos#478]
Hi there

I am trying to export dicom as csv and understand that the Export ROI plugin should allow me to do this. However I cannot see an export option to allow me to do so, despite the plugin being active. Please see images for explanation

Any assistance is greatly appreciated. 

![Screen Shot 2019-04-17 at 14 02 40](https://user-images.githubusercontent.com/49404294/56290206-8af70800-611a-11e9-8c31-78e8bb0c9937.jpg)
![Screen Shot 2019-04-17 at 14 02 59](https://user-images.githubusercontent.com/49404294/56290207-8b8f9e80-611a-11e9-86a3-d8971d641571.jpg)
![Screen Shot 2019-04-17 at 14 03 25](https://user-images.githubusercontent.com/49404294/56290208-8b8f9e80-611a-11e9-99e6-b835a0c9c747.jpg)

**Comment by JoaoSantinha** [comment]
Can you try to open one of those images using *2D Viewer* then draw a ROI
(just to make sure that the plugin is enabled - not talking about the
status on the plugin manager but that you can selected on the plugins *ROI
Tools menu*) and then try to execute the plugin.

**Comment by gs503** [comment]
Joao- fantastic- that's worked. Thanks very much for your help
