### ISSUE TITLE
Auto query retrive set up from "Network menu"

### ISSUE THREAD

**Issue by TonyTaff** [horosproject/horos#48]
When setting up OSIRI-LX!V to auto query and retrieve i all works until the  app is restarted when the autoretrieve button is de selected   Bit of a problem when you expect it to restart following a power outage   ..

<img width="444" alt="capture009" src="https://cloud.githubusercontent.com/assets/16492012/12066246/dd92173e-afb2-11e5-9593-11c8c28791f1.PNG">

**Comment by fvpolpeta** [comment]
Hi;

Have you selected the option "Restart DICOM Auto Query & Retrieve settings at launch" ?

In Horos, it's located in Preferences->Locations.

BR

**Comment by TonyTaff** [comment]
Hello and thank you you for your response.

I tried your suggestion  unfortunately it DID NOT help.

Just to be sure that we are talking about the same thing.

Under Network > Auto Query/Retrieve Window

there is the ability to set the auto retrieve  This is reset each time 
you relaunch HOROS
and it will only query the target machine

text

Hmm I might have solved my issue.. I noticed that there is a default 
instance option

I added my own custom  instance and deleted  the default instance 
option   now it seems to remember my setting..

On 1/6/2016 7:00 PM, Fauze Polpeta wrote:

> Hi;
> 
> Have you selected the option "Restart DICOM Auto Query & Retrieve 
> settings at launch" ?
> 
> In Horos, it's located in Preferences->Locations.
> 
> BR
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/horosproject/horos/issues/48#issuecomment-169503661.

## 

Tony Evans Enterprises Inc
tonyevans1@verizon.net
tel: 727 480 7813

**Comment by fvpolpeta** [comment]
User has solved the issue by creating it's own custom instance and deleting the default instance.
