### ISSUE TITLE
Unable to create new ROI

### ISSUE THREAD

**Issue by vivekstorm** [horosproject/horos#484]
for(ViewerController *v in ViewerController.getDisplayed2DViewers){
      NSMutableArray *roiSeriesList=[v roiList];

       for(int j=0;j<[roiSeriesList count];j++){

                NSMutableArray *roiImageList=[roiSeriesList objectAtIndex:j];
                for(int i=0;i<[roiImageList count];i++)
                {
                    ROI *newcurr=[v newROI:tMesure];
                }
       } }

I'm not able to create new ROI. When I tried create new roi using above line I get error

**"[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array"**

**Comment by JoaoSantinha** [comment]
Hi Vivek,

The error is because you don't have any ROI so you cannot iterate over the array of ROIs. 

Here you have a nice tutorial that will help you [tMeasure](https://osirixpluginbasics.wordpress.com/2011/08/05/roi-tmeasure/)

Cheers
