### ISSUE TITLE
1.1.6 is slow

### ISSUE THREAD

**Issue by cryanvmd** [horosproject/horos#52]
Just upgraded to Horos version 1.1.6.  Images take significantly longer to open and to switch between images in a series.  Horos hangs with spinning wheel when trying to close a study.  Much worse performance than 1.1.4.  
Running OS X el Capitan (10.11.2)

**Comment by fvpolpeta** [comment]
Please try this nightly build and inform us how it performs:

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.app.zip

BR
