### ISSUE TITLE
Color coded images are displayed with wrong colors

### ISSUE THREAD

**Issue by Paskob** [horosproject/horos#53]
Most of the type they seem to come out with a green color. For example try importing this DICOM into HOROS and OSIRIX to see what I mean.

**Comment by Paskob** [comment]
Sorry I decided not to upload that last file since it was impossible to annonomize properly.

**Comment by fvpolpeta** [comment]
Without the DICOM file is a bit difficult to trace that. At least, send a screenshot with no visible patient data.

BR

**Comment by Paskob** [comment]
<img width="1252" alt="screen shot 2016-02-04 at 9 53 19 pm" src="https://cloud.githubusercontent.com/assets/16972038/12813036/bcb84fb8-cb89-11e5-8eba-222e09c681dd.png">
Hope this helps. Can I email you a dicom file privately?

**Comment by Paskob** [comment]
![screen shot 2016-02-04 at 9 53 19 pm](https://cloud.githubusercontent.com/assets/16972038/12813112/11b10596-cb8a-11e5-97a4-5f55fe854948.jpg)
uploading in JPG incase png does not work

**Comment by Paskob** [comment]
Ok I've uploaded a an anonymised test case of the 'Green Goblin error' with DICOM files. Hopefully this helps. The Green Goblin only appears with Horos and not Osirix
[Test_Case_No__1.zip](https://github.com/horosproject/horos/files/135414/Test_Case_No__1.zip)

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

To help you with colors see:

https://github.com/horosproject/horos/issues/88

Best Regards

Fauze
