### ISSUE TITLE
Rotate a "oval" from ROI

### ISSUE THREAD

**Issue by simongeek** [horosproject/horos#536]
Hi,

I have an issue with rotating an "oval" ROI. How to do it?

**Comment by JoaoSantinha** [comment]
Hi Szymon,

Try option+command keys and it should allow you to rotate both oval or
rectangle ROIs

Cheers,
Joao

**Comment by simongeek** [comment]
Thanks @JoaoSantinha !

It works!
Best wishes,
Szymon
