### ISSUE TITLE
Can't build due to OpenSSL config error

### ISSUE THREAD

**Issue by Caine85** [horosproject/horos#550]
Hi everybody!

I'm trying to build the Horos project on Xcode 11.3.1 and macOS 10.15.3 Catalina. The build process stops almost immediately with the following error:

`Horos/Scripts/OpenSSL/Config.sh: line 76: ./config: No such file or directory`

Do you have any suggestions on how to solve it?

Thank you so much!

**Comment by aglv** [comment]
I think you didn't clone the Horos project recursively. OpenSSL just happens to be the first submodule the build system tries to build.

cd to the local cloned Horos repository path and run this:

git submodule update --init --recursive

**Comment by Caine85** [comment]
Hi @aglv, thank you very much for your very quick reply! 

The problem was that I cloned the repository via GitHub's "Clone or download" green button which apparently didn't clone all the necessary files. 

Trying to clone the repository through
`git clone https://github.com/horosproject/horos.git`
everything worked regularly. 

Thank you very much and excuse me for the inconvenience.

> I think you didn't clone the Horos project recursively. OpenSSL just happens to be the first submodule the build system tries to build. cd to the local cloned Horos repository path and run this: git submodule update --init --recursive
> […](#)
