### ISSUE TITLE
Horos is crashing while launching with CTable:AddEntry

### ISSUE THREAD

**Issue by nasirzeeshan** [horosproject/horos#572]
![Horos_Crash](https://user-images.githubusercontent.com/31031198/82132543-41d02680-97fa-11ea-9a93-6005d60eba57.png)

When i try to Run Horos 4, latest available version for Mac 10.11 i am getting EXC_BAD_ACCESS at CTable::AddEntry procedure in lookuptable.h

Any ideas ?

**Comment by jensen0914** [comment]
It would be helpful to add what you were doing that led to this issue. For
example, does it occur while launching Horos? Or opening a study in the
viewer?

And as you shared a debugger window, are you compiling this yourself? I
cannot get Horos to run when compiled with Xcode 11.4 but it does with a
code 11.3.1 on macOS 11.15.4.

**Comment by nasirzeeshan** [comment]
Thanks for reply
yes i tried to launch Horos from Xcode, and my Xcode version is 11.4.1 and i am using macOS 10.15.4 Catalina.
So which Xcode version you recommend on my Mac version 10.15 ?

Regards,
Nasir Zeeshan

**Comment by jensen0914** [comment]
I’ve had good luck using Xcode 11.3.1. I haven’t had time to figure out why
using Xcode 11.4+ results in this crash.

**Comment by nasirzeeshan** [comment]
Worked with 11.3.1, Thank you very much, you saved my day.
