### ISSUE TITLE
3D functions are not available

### ISSUE THREAD

**Issue by DinoDragons** [horosproject/horos#573]
I import a set of tif (and jpg) images to Horos. However, all 3D viewer functions are dimmed. Wondering what's wrong.
Please help.

**Comment by DD-P** [comment]
TIFF and JPEG images do not contain the required meta-data.  In particular, there will be no size and position data (e.g. z-axis location).  For that you will need DICOM image data (which will themselves contain the image as TIFF or JPEG etc.)

**Comment by jensen0914** [comment]
This is the expected behavior and not a bug, as there is not the required information in JPEG/TIFF to provide 3D functionality.

**Comment by DinoDragons** [comment]
In the past, I was able to use Plugin/JPG to DICOM to import jpg or tiff images to run. This was since the good old days of OsiriX 4. And now, even the latest OsiriX lite will handle it this way. The older version of Horos will do the same.
However, it won't work anymore. Why?

**Comment by jensen0914** [comment]
The following worked for me using Horos 4.0.0 RC4 on macOS 10.15.4:
1) Exported the first 10 slices from a 3D series to a folder as JPEG files.
2) Selected a different study in the database window.
3) Used the Horos JPEG to DICOM plugin to select the 10 JPEG files and import them with the Meta-Data setting set to "From the selected study in Database window"
4) Opened imported series in 2D viewer, selected "3D MPR" and get a "Calibrate the dataset:" dialog.
5) Entered values for pixel sizes and clicked OK.
6) 3D MPR window appears with expected output.

Maybe launch Horos from a Terminal command prompt to see if there are any console messages that provide more details for you.

**Comment by DinoDragons** [comment]
Thank Todd,
I will try. So selection of "From the selected study in Database window" is important?
Smiles,  Prof. Timothy Huang    黃大一教授 台灣新北市新店區23156安康路三段525巷43號
43, Lane 525, Sec. 3, AnKang Road, XinDian District, New Taipei City, Taiwan, ROC     23156       
tel: +886-2-2214-0517 Portable: +886-926-684-464, +86-177-6773-4226
 

    在 2020年5月20日 星期三 下午11:00:16 [GMT+8]， Todd Jensen<notifications@github.com> 寫道：  
 
 


The following worked for me using Horos 4.0.0 RC4 on macOS 10.15.4:
   
   - Exported the first 10 slices from a 3D series to a folder as JPEG files.
   - Selected a different study in the database window.
   - Used the Horos JPEG to DICOM plugin to select the 10 JPEG files and import them with the Meta-Data setting set to "From the selected study in Database window"
   - Opened imported series in 2D viewer, selected "3D MPR" and get a "Calibrate the dataset:" dialog.
   - Entered values for pixel sizes and clicked OK.
   - 3D MPR window appears with expected output.

Maybe launch Horos from a Terminal command prompt to see if there are any console messages that provide more details for you.

**Comment by jensen0914** [comment]
"So selection of "From the selected study in Database window" is important?"

I'm not sure because I didn't dig into the code - but that worked for me. Maybe because it can find position and orientation info to add. You may also need a minimum number of slices.

**Comment by DinoDragons** [comment]
Ha, just found out that selection is dimmed.
Smiles,  Prof. Timothy Huang    黃大一教授 台灣新北市新店區23156安康路三段525巷43號
43, Lane 525, Sec. 3, AnKang Road, XinDian District, New Taipei City, Taiwan, ROC     23156       
tel: +886-2-2214-0517 Portable: +886-926-684-464, +86-177-6773-4226
 

    在 2020年5月20日 星期三 下午11:43:11 [GMT+8]， Todd Jensen<notifications@github.com> 寫道：  
 
 


"So selection of "From the selected study in Database window" is important?"

I'm not sure because I didn't dig into the code - but that worked for me. Maybe because it can find position and orientation info to add. You may also need a minimum number of slices.

**Comment by DinoDragons** [comment]
Still can NOT get it working.
Smiles,  Prof. Timothy Huang    黃大一教授 台灣新北市新店區23156安康路三段525巷43號
43, Lane 525, Sec. 3, AnKang Road, XinDian District, New Taipei City, Taiwan, ROC     23156       
tel: +886-2-2214-0517 Portable: +886-926-684-464, +86-177-6773-4226
 

    在 2020年5月20日 星期三 下午11:43:11 [GMT+8]， Todd Jensen<notifications@github.com> 寫道：  
 
 


"So selection of "From the selected study in Database window" is important?"

I'm not sure because I didn't dig into the code - but that worked for me. Maybe because it can find position and orientation info to add. You may also need a minimum number of slices.

**Comment by DinoDragons** [comment]
Still can NOT get it working.
