### ISSUE TITLE
MRI images shown as Black to White gradient

### ISSUE THREAD

**Issue by aazidizel** [horosproject/horos#574]
DICOM images from Hitachi Airis II MRI system are shown as B & W gradient on HOROS 3.3.6 and 3.3.5 running on High Sierra 10.13.6. The sample files are attached as zip.
[Anonymized - 01-02-06.zip](https://github.com/horosproject/horos/files/4714944/Anonymized.-.01-02-06.zip)

**Comment by Rest-Of-World** [comment]
Hi, i check your images by HOROS 3.3.6 on **Catalina**.

![sample](https://user-images.githubusercontent.com/66294919/83484536-1af33f00-a4e0-11ea-9008-10be634425ba.png)

But there is no items on menu bar.

**Comment by aazidizel** [comment]
But is the menu bar related to the images? it should be displayed by the application it self.

**Comment by aazidizel** [comment]
Removed and reinstalled the 3.3.6 version of Horos second time and the images and the tool bars are correctly displayed.
