### ISSUE TITLE
Fly through screenshot error - 4.0.0 RC4  (macOS 10.11+)

### ISSUE THREAD

**Issue by gustavusc** [horosproject/horos#576]
Hi, new here

I got to upgrade from 3.3.6 to 4.0.0 RC4 because the annotation issue that have been reported. Every thing work fine in Catalina 10.15.4. But when doing an animation with the tool fly through, every time I screenshot a movement (by using the + button) the screenshot show my model in the higher right corner, but the model doesn't move. If I continue with the animation, compute and export as a video, the model appears in the higher right corner. I did not find any solution so I return to the 3.36 version and the animation went great. The same issue happened with other studies, and the model appears in different corners, I'm not sure what is causing that behavior.  

Let me know if you need more information about any settings or workflow, I hope when this version goes as official the problem will be fix!

Thanks for everything 

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/42424722/84705973-da54e600-af21-11ea-8984-4b1c00ad010b.png">

**Comment by jensen0914** [comment]
This may be related to another issue fixed for the 3D viewer (#533) in Horos 4.0.0RC4 that has to do with Retina screen coordinates as the root cause.

**Comment by gustavusc** [comment]
Thanks! it fix the problem, and the animation looks just as good. However the miss alignment issue in the scissor tool still present. But you can easily adapt to it.

**Comment by gustavusc** [comment]
Thanks! it fix the problem, and the animation looks just as good. However the miss alignment issue in the scissor tool still present. But you can easily adapt to it.
