### ISSUE TITLE
How to display HU

### ISSUE THREAD

**Issue by ClaraPC** [horosproject/horos#579]
<img width="425" alt="image" src="https://user-images.githubusercontent.com/67387250/85608295-3839aa00-b655-11ea-97c5-f34dc80c8e10.png">

Hi, how could I see the Hounsfield units without creating an oval or rectangle? 
I am used to see them right where the green arrow is pointing while I move the cursor. 
Thank you!

**Comment by jensen0914** [comment]
This is duplicate of #535.
