### ISSUE TITLE
[DICOMExport setSourceDicomImage:] error

### ISSUE THREAD

**Issue by jennifersteeden** [horosproject/horos#589]
I am facing a similar problem to issue #64 from 2016....

I am trying to export some data using the 'setSourceDicomImage' function - however it return an error:

[DICOMExport setSourceDicomImage:]: unrecognized selector sent to instance 0x600003d12fd0

The same plugin works fine in OsiriX. The only difference I see is that the DicomImage sent from Horos is type 'DicomImage_Image_2' whereas from Osirix is just 'DicomImage_Image_'

Any help would be appreciated.
Thanks,
Jenny

**Comment by aglv** [comment]
Horos doesn't support `setSourceDicomImage`.

There is this alternative:
`- (void)setSourceFile:(NSString *)isource;`

And Osirix has this:
```
- (void) setSourceFile:(NSString*) isource __deprecated;
- (void) setSourceDicomImage:(DicomImage*) i;
```

So, your easy solution is to use the deprecated `setSourceFile:image.completePathResolved`.

**Comment by jennifersteeden** [comment]
Thank you very much for your swift response. Worked perfectly!

**Comment by jensen0914** [comment]
For future proofing your code, you can test if the deprecated method is available before using it, and fallback to the other if it is not available. Something like:

```
if ( [ [ DICOMExport class ] respondsToSelector : @selector( setSourceDicomImage: ) ] )
{
   [ exportObj setSourceDicomImage : image ];
}
else
{
   [exportObj setSourceFile: imagePath ];
}
```
