### ISSUE TITLE
Export H.264 movie

### ISSUE THREAD

**Issue by cryanvmd** [horosproject/horos#59]
Exporting an ultrasound cine clip in Horos as an H.264 encoded movie clip does not work.  Importing same study into Osirix and exporting as an H.264 movie clip works just fine.  Is this a known bug?

**Comment by fvpolpeta** [comment]
Please provide us with an ultrasound series and a step-by-step of how you are trying to export the h264 movie.

Thanks in advance.

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon. 

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

**Comment by ky-tech-guy** [comment]
I am having the same problem.  I am using Horos 2K v2.0.1.  I attached a link to a dicom image set that I am using.  When I open the images series i click on the axial images and then hit export. Try to export them as H.264.  A file will actually appear on my desktop saying DICOM.mp4 but when I go to open the file with VLC it wont allow me.  When I click on get info under the DICOM.mp4 it says the file size is 0 MB.

https://drive.google.com/open?id=0B8MF_LlXXetNUkZkcUNNeUVIa1k
