### ISSUE TITLE
I accidentaly deleted some of the studies in my database, how can I get them back?

### ISSUE THREAD

**Issue by drsamrom** [horosproject/horos#590]

**Comment by jensen0914** [comment]
This is not a bug but a user action. I suggest in the future using backup software that will allow you to reset the files.

**Comment by jensen0914** [comment]
Also, reference articles on the web such as https://www.howtogeek.com/361816/how-to-recover-deleted-files-on-mac/ to learn how to recover deleted fiiles. You may be able to at least recover the actual image files stored and re-import them.
