### ISSUE TITLE
Help Understanding Pixel spacing versus Millimeter spacing on Horos. 

### ISSUE THREAD

**Issue by hawkeyedesi** [horosproject/horos#598]
I am trying to compute the real physical spacing (in mm) of a distance measured using the Length Tool. I start off by drawing a few calibration lines of fixed length ( = 5mm) and I export that as an XML file. From the metadata of the Dicom image, I see the `ImagerPixelSpacing` Tag `0018,1164` which has a value of `0.154`  

After exporting, I see the `<key>Point_mm</key>` in the XML it shows up at `x1 = 3.5716, x2 = 8.5254` which when subtracted gives me the 5mm measurement correctly. Now the corresponding <key>Point_px</key> for the same are `x1 = 37.2860, x2 = 89.6561`. When subtracted I get `52.3701` pixels. Logically multiplying this by the Pixel spacing from the metadata should give me the 5mm. However it gives me `52.3701 * 0.154 = 8.06`.  Clearly, the pixel spacing being used is something different (`5/52.3701 = 0.0954`)

My Question: Where is this information coming from and why is it different from the Dicom metadata tag shown? What am I missing? Any help would be appreciated.

**Comment by jensen0914** [comment]
Looking at the code for the Export ROI plugin, I see the Point_px values are a set of (x,y) values. The code uses these same (x,y) values to convert to the Point_mm values via the DCMPix covertPix method. And that method may rotate the (x,y) values based on the image orientation value. So the "x" and "y"s in the Point_mm and Point_px may not be in the same plane so a simple subtraction will not work, especially if there if y1 is not the same as y2.

If you could share the entire XML and provide the ImageOrientationPatient (0x0020,0x0037) value from the DICOM meta-data then I can look at it deeper.

You should use the distance formula to compute the actual pixels between the Point_px values using:

d = sqrt( (x1-x2)^2 + (y1-y2)^2 )

**Comment by hawkeyedesi** [comment]
> If you could share the entire XML and provide the ImageOrientationPatient (0x0020,0x0037) value from the DICOM meta-data then I can look at it deeper.

Interestingly the ImageOrientationPatient (0020,0037) for this DICOM does not exist. There is a Patient Orientation (0020, 0020) but that is also empty. Is there any other DICOM tag it uses? 

Embedded XML file below: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Images</key>
	<array>
		<dict>
			<key>ImageIndex</key>
			<integer>0</integer>
			<key>NumberOfROIs</key>
			<integer>1</integer>
			<key>ROIs</key>
			<array>
				<dict>
					<key>Area</key>
					<real>0.0</real>
					<key>Center</key>
					<string>(7.378883, 36.941978, 0.000000)</string>
					<key>Dev</key>
					<real>0.0</real>
					<key>IndexInImage</key>
					<integer>0</integer>
					<key>Length</key>
					<real>0.50050574541091919</real>
					<key>Max</key>
					<real>0.0</real>
					<key>Mean</key>
					<real>0.0</real>
					<key>Min</key>
					<real>0.0</real>
					<key>Name</key>
					<string>ROI 1</string>
					<key>NumberOfPoints</key>
					<integer>2</integer>
					<key>Point_mm</key>
					<array>
						<string>(4.878973, 36.827530, 0.000000)</string>
						<string>(9.878793, 37.056423, 0.000000)</string>
					</array>
					<key>Point_px</key>
					<array>
						<string>(51.522308, 385.627304)</string>
						<string>(103.808395, 388.020996)</string>
					</array>
					<key>Total</key>
					<real>0.0</real>
					<key>Type</key>
					<integer>5</integer>
				</dict>
			</array>
		</dict>
	</array>
</dict>
</plist>

```

> So the "x" and "y"s in the Point_mm and Point_px may not be in the same plane so a simple subtraction will not work, especially if there if y1 is not the same as y2. You should use the distance formula to compute the actual pixels between the Point_px values using: d = sqrt( (x1-x2)^2 + (y1-y2)^2 )

Good point. I agree. So for the example line: ` y1=36.827530, y2=37.056423` are almost the same. That's how I got away with a simple subtraction. 

Thanks for helping out. Without the orientation, I am still not sure where the `0.0954` spacing is coming from.

**Comment by hawkeyedesi** [comment]
Hi @jensen0914 
Any leads on why this could be happening? Appreciate your inputs on this. 

Thanks.
