### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0xfffffff902ca3ec0) when compiling Horos on XCode 12.1

### ISSUE THREAD

**Issue by hawkeyedesi** [horosproject/horos#602]
When I compile Horos on XCode 12.1 I get the following error: 

```
Horos`CTable::AddEntry:
    0x100a6bd40 <+0>:  pushq  %rbp
    0x100a6bd41 <+1>:  movq   %rsp, %rbp
    0x100a6bd44 <+4>:  movq   %rcx, %r8
    0x100a6bd47 <+7>:  movl   $0x8, %ecx
    0x100a6bd4c <+12>: subq   %r8, %rcx
    0x100a6bd4f <+15>: movl   $0x1, %eax
    0x100a6bd54 <+20>: shlq   %cl, %rax
    0x100a6bd57 <+23>: cmpq   $0x3f, %rcx
    0x100a6bd5b <+27>: je     0x100a6bd93               ; <+83>
    0x100a6bd5d <+29>: movzbl %sil, %esi
    0x100a6bd61 <+33>: shll   %cl, %esi
    0x100a6bd63 <+35>: movslq %esi, %rcx
    0x100a6bd66 <+38>: shlq   $0x4, %rcx
    0x100a6bd6a <+42>: leaq   0x8(%rdi,%rcx), %rcx
    0x100a6bd6f <+47>: xorl   %esi, %esi
    0x100a6bd71 <+49>: nopw   %cs:(%rax,%rax)
    0x100a6bd7b <+59>: nopl   (%rax,%rax)
->  0x100a6bd80 <+64>: movq   %rdx, -0x8(%rcx)
    0x100a6bd84 <+68>: movq   %r8, (%rcx)
    0x100a6bd87 <+71>: incq   %rsi
    0x100a6bd8a <+74>: addq   $0x10, %rcx
    0x100a6bd8e <+78>: cmpq   %rax, %rsi
    0x100a6bd91 <+81>: jl     0x100a6bd80               ; <+64>
    0x100a6bd93 <+83>: popq   %rbp
    0x100a6bd94 <+84>: retq   
    0x100a6bd95 <+85>: nopw   %cs:(%rax,%rax)
    0x100a6bd9f <+95>: nop    
```

The `Thread 1: EXC_BAD_ACCESS (code=1, address=0xfffffff902ca3ec0)` bad access occurs on the movq shown by the arrow. 

Two questions here: 
1. How do I debug/solve this issue? Appreciate any help on this. 

2. This is a newbie question: How do I see the source code for this error? Why do I only see the stack trace and not the line which causes this break? 

I am running this on a MacBook Pro (13-inch, 2018) running macOS Catalina Version 10.15.7, XCode Version 12.1 (12A7403)

**Comment by hawkeyedesi** [comment]
Downgrading to  v11.3.1 helped solve this. 

https://github.com/horosproject/horos/issues/604#issuecomment-721718243

**Comment by TheDagger** [comment]
How do you downgrade it?

**Comment by hawkeyedesi** [comment]
I downloaded it from here: https://developer.apple.com/download/more/?&name=Xcode

**Comment by TheDagger** [comment]
Thanks this did indeed work! Any idea why this fixes it?
