### ISSUE TITLE
Is there a way to implement the cmove protocol

### ISSUE THREAD

**Issue by doggydoc** [horosproject/horos#610]
coming from Osirix HD, I was just trying out the horos app and was wondering if the cmove protocol was an option for Horos, too, as my pacs does not respond to the cget command. Or is there a work around ? Please dont ask me too many details, as I`m a vet with hardly any specific software knowledge.
best and compliments for your work.

Matthias

**Comment by jensen0914** [comment]
You should be able to specify the type of retrieve protocol in the Horos->Preferences->Listener dialog as shown below:

<img width="829" alt="Screen Shot 2020-11-29 at 2 40 00 PM" src="https://user-images.githubusercontent.com/17097762/100553068-115d5080-3251-11eb-8620-3f52c241a331.png">

I am closing this issue as C-MOVE is implemented.

Regards,

Todd Jensen, PhD
Jensen Informatics LLC

**Comment by doggydoc** [comment]
Hallo Todd, thanks for your reply. I’m sorry I didn’t specify I was referring to the horos mobile app. There cmove  can’t be selected as retrieve protocol.

**Comment by gmichal** [comment]
Yes it does. It can be specified in the DICOM node under 'Retrieve mode'. This ticket should be closed as the Horos Project git is not the appropriate place to report bug reports for the Horos Mobile™ app. Bug reports and feedback are accepted via in-app contact form for the mobile app.

**Comment by icatSolutions** [comment]
This issue should be closed. The best way to send your feedback for the Horos Mobile™ app, is via the in-app feedback form.
For reference this the Horos Mobile™ app supports CMOVE under the DICOM Node Editor in the 'Retrieve' section.
