### ISSUE TITLE
does ViewerController *pixList take raw pixel_array values?

### ISSUE THREAD

**Issue by bkonk** [horosproject/horos#627]
When looking at  *pixList values from a 2d viewer, does this just include the original values from the dicom pixel_array or PixelData? Or does this take displayed values, adjusting for rescale slope and rescale intercept -- and including any window-level adjustments?

**Comment by jensen0914** [comment]
General comment: this is not a bug/issue report but a question that is more suited for the general Horos Google Group.

But, to answer your question, the float array are the original pixel values from the DICOM file AFTER the rescale slope and rescale intercept have been applied but BEFORE the window-level settings are applied.

**Comment by bkonk** [comment]
Thank you! and sorry for the poorly-suited question..
