### ISSUE TITLE
ROIs and DICOM pixelmatrix dimension problem

### ISSUE THREAD

**Issue by jaimecorton** [horosproject/horos#636]
Hi again !

I'm Jaime,

I'm working with MRI images and their ROIs, I'm having some issues with dimensionality of the Binary Mask of the ROI and the DICOM. ROI pixel matrix has more pixels per image than DICOM image. I'm wondering if there's any possibility of these 2 pixel matrix ( DICOM and ROI) match with themselves (DICOM 512x512 pixels and ROI binary mask of 512x512 pixels) I've read that CreateROIMask plugin is a good candidate, but any kind of expertise or knowledge about this would be completely helpful.

Thanks to everybody in advance

Jaime

**Comment by jaimecorton** [comment]
I'm using specifically a 2009 iMac of 27 inches with macOS HIGH SIERRA 10.13.6

**Comment by sorenchr2011** [comment]
What are you using at the moment to get a binary ROI mask?
Can you elaborate on this:
" I'm wondering if there's any possibility of these 2 pixel matrix ( DICOM
and ROI) match with themselves (DICOM 512x512 pixels and ROI binary mask of
512x512 pixels)"

**Comment by jaimecorton** [comment]
I'm sorry, I explained the issue unclearly. 

For the ROI I'm using the default Brush tool. The dimension of the pixel matrix of the ROI created is different than the original DICOM image. In other words if i got a DICOM image of 512x512 pixels (512 Pixels in width and 512 pixels in height) the generated ROI does not match with this 512x512 pixel matrix since it is overlapped within the image on a higher order matrix (for example 700x700 pixels). So pixel resolution of the Brush tool generated ROIs is higher than the DICOM image pixel resolution. The issue here is that when exporting all that to an script in order to apply some deep learning algorithms the dimensionality of ROI and DICOM image needs to be strictly the same(512x512pixels for both ROI and DICOM as I have said before.)

Ideally I would obtain a binary mask (ROI) with the same dimension of the DICOM image, or instead of the binary mask another DICOM Image with the ROI information and the same size of the DICOM image.

So the key points here are the following:
-Is there any way of interpolating the ROI to match the same pixelmatrix dimensionality of the DICOM image?
-Is there any way of having a DICOM image similar in size to the DICOM image on the background instead of having a .ROI .XML .CSV that contains the ROI information desired

I'm so sorry, English is not my mother tongue, so I apologize for this. If this is not clear enough I will find the way of explain myself better, just let me now.

Jaime

**Comment by sorenchr2011** [comment]
Hi Jaime,
 Ok I understand. I actually did not know that the brush tool operates on a
higher res image than the input data - I can't see any reason for this.
In any case, here's a plugin that converts outlines (I don't think it works
on brush ROIs, but usually outlines are less time consuming to do):
https://github.com/horosproject/horosplugins/tree/master/VoxelVolume
It produces DICOM binary output with same dimensions as the DICOM input. So
it essentially just rasterizes the outline ROI.
I can send you a built version if needed, but you can build it yourself
from the link using xcode.
Soren

**Comment by jaimecorton** [comment]
Thanks Soren!

One last question, how could I download the plugin from github link that you send me? I'm not familiarized with it. I used to download directly the .horosplugin file and then open it with Horos so that the plugin is uploaded to the plugin library. A brief explanation about the download would be completely usefull for me.

Thanks again!

Jaime

**Comment by jaimecorton** [comment]
PD: I have never used Xcode :(

**Comment by sorenchr2011** [comment]
The github link has the source code. You can then use xcode to build a
plugin from the sources. That's handy if you want to change the plugin or
inspect what it does.
I can send the plugin binary if you provide an email address.
Which MacOs are you using?

**Comment by jaimecorton** [comment]
I'll be pleased if you send me the info to  (j.corton.2017@alumnos.urjc.es)

I'm using MacOs high sierra 10.13.6

Thanks for all Soren

Jaime

**Comment by jensen0914** [comment]
This is not an issue but a misunderstanding of ROIs. I am going to close it as there are multiple ways to export the ROI into a mask image with the same resolution.

Update the plugin code above to do what your want.
OR Use a commercial plugin like Imaging Biometrics IB Delta Suite to export a mask image.
OR Create DICOM images with 0/1 as pixel values from the ROIs, following these steps. 

1. In the 2D Viewer, select at least one ROI that defines the mask.
2. Click on "ROI→Set Pixel Values to..." open pixel value change dialog.
3. In dialog:
- Select  "ROIs with same name as the selected ROI" or "All ROIs".
- Select "Outside ROIs"
- Check box next to "if current value is larger than".
- Uncheck box next to "if current value is smaller than"
- Select "To this new value" and set value to 0.
- Click "OK"
4. Image should now have zeros outside ROIs (don't worry, it is just in memory and the original values are still in the file). Now repeat steps 2 and 3 but use the following settings:
- Select  "ROIs with same name as the selected ROI" or "All ROIs".
- Select "Inside ROIs"
- Check box next to "if current value is larger than".
- Uncheck box next to "if current value is smaller than"
- Select "To this new value" and set value to 1.
- Click "OK"
5. Now you have an image that is mask in the original image. Now click on "File→Export→Export as DICOM file(s)" to open export dialog.
6. In dialog, use the following settings:
- Select "All images of the series, including" (verify interval=1, from=1, to=<number of slices>)
- Select "As stored in memory in 16-bit BW).
- Set Series name to something you want for the mask image.
- Click "OK"

You will now have a new DICOM series in the same resolution as the original series but with 0 and 1s for pixel values. You can export that how you like to convert to other image formats as needed.
