### ISSUE TITLE
Crash on MacBook Pro 16' 2019

### ISSUE THREAD

**Issue by xsestech** [horosproject/horos#649]
Hello, I have MacBook Pro 16' 2019 with a core i7 CPU. Since I have installed mac os big sir I can't open Horos. It just crushes. Apple report says that I have exception EXC_BAD_ACCESS (SIGSEGV).
I can post a full crash report if you need to,

**Comment by jensen0914** [comment]
Please try the workaround I documented at https://github.com/horosproject/horos/issues/639#issuecomment-821813019

**Comment by xsestech** [comment]
Thank you! I couldn't solve this problem for a long time.
