### ISSUE TITLE
dmg url

### ISSUE THREAD

**Issue by securingmom** [horosproject/horos#650]
hi there.  I can't find the next step to download horos from your live site

![Screenshot_2021-05-13 Download – Horos Project](https://user-images.githubusercontent.com/76798008/118099638-06444a00-b3c5-11eb-875b-b5136548ef19.png)

This is a Catalina macbook pro i9.  I'm not interested in BigSur anytime soon; I prefer working apps.

May I have a dmg url?

**Comment by jensen0914** [comment]
Hi, click the **Download Horos** button to fill out a form and you will be sent a link. Or use this direct link to get to the form: [https://horosproject.org/download-horos/](https://horosproject.org/download-horos/).

Todd Jensen, PhD
Jensen Informatics LLC

**Comment by AnilaHernandez** [comment]
Hi Todd,

The correct link is:

https://horosproject.org/download/
