### ISSUE TITLE
how to launch  horos from Browser to load images from Remote server

### ISSUE THREAD

**Issue by arunjoshtech** [horosproject/horos#683]
Hi,
How to launch Horos from browser to launch and load images from remote server like web protocol given in Weasis viewer.

**Comment by jensen0914** [comment]
Horos uses the same scheme as OsiriX, but replace "osirix:" with "horos:" in URLs:

[https://www.osirix-viewer.com/resources/ris-integration/](https://www.osirix-viewer.com/resources/ris-integration/)

**Comment by jensen0914** [comment]
Make sure you have the URL listener enabled in the Preferences:
<img width="635" alt="Screen Shot 2021-12-20 at 12 53 07 PM" src="https://user-images.githubusercontent.com/17097762/146818408-7f3e28df-9316-4819-833c-52c0ba97ee89.png">

**Comment by arunjoshtech** [comment]
Thanks for the guidance.
