### ISSUE TITLE
Why is it slower than Osirix Lite?

### ISSUE THREAD

**Issue by ashadibudi** [horosproject/horos#69]
Hi, I am using Horos 1.1.7 on Elcapitan Macbook 12

I notice Horos 1.1.7 that running at 64 bit significant speed slower for the  than Osirix Lite 32 bit, when opening a CT.

I load a simple 2D axial CT images consist of 208 slices only. Horos takes about 14 seconds to fully 100% load the 2D images. While its only takes about 4 seconds in Osirix lite.

But the strange thing is.. When run a 3D volume rendering on the exact same images. Horos & Osirix Lite have exact same time at 4 seconds to fully load the 3d rendering.

How can I know that Horos app in my mac already run the 64bit?
Or this is also a bug?

**Comment by fvpolpeta** [comment]
This is related to the fact the image CODECs used by Horos are fully derived from open source projects. OsiriX relies on third-party commercial CODECs, which are faster than ours. CODECs are specifically used in load time. We are working to improve this. 

Horos is built only in 64-bit. For sure you are running it in 64-bit.
