### ISSUE TITLE
images won't stop cycling

### ISSUE THREAD

**Issue by mneal4863** [horosproject/horos#706]
When I click on a study, the images won't stop cycling in a continuous loop.

**Comment by jensen0914** [comment]
If this is the database window, did you try clicking the space bar or uncheck the play checkbox near the image preview?

**Comment by mneal4863** [comment]
THANK YOU, the space bar did the trick :)

Mary C Neal, MD
  .change begins with an individual.  w.b.neal 3

~ Please consider the environment before printing this email or its attachments ~




 

    On Saturday, July 9, 2022 at 01:03:23 PM MDT, Todd Jensen ***@***.***> wrote:  
 
 


If this is the database window, did you try clicking the space bar or uncheck the play checkbox near the image preview?
