### ISSUE TITLE
De Identification Error

### ISSUE THREAD

**Issue by spersohn** [horosproject/horos#71]
I have had problems with MRI dataset being de-identified using the Anonymize feature producing corrupt images in the data sets.  The original datasets are fine with no errors, whereas the newly de-identified datasets have corrupted images.  I have only seen this on MRI images to date.

Thanks,
Scott

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze
