### ISSUE TITLE
Editing DICOM content

### ISSUE THREAD

**Issue by justinroberts22** [horosproject/horos#72]
Whenever I try to edit DICOM content and apply the changes, my series will get multiple blank images that break up the sequence.  I am running Horos v1.1.6.  

Is this a known bug?

![screen shot 2016-03-02 at 2 49 31 pm](https://cloud.githubusercontent.com/assets/16482022/13505350/a200de92-e12d-11e5-81c0-4eb7c5610c55.png)

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze
