### ISSUE TITLE
Unable to downloaad Horos

### ISSUE THREAD

**Issue by JoseMPalomo** [horosproject/horos#742]
I tried to download Horos, was then asked to donate, what I did and was asked my personal information, age, address, profession, MasterCard number, expiring date and code and ... then I was prompted to create a PayPal account.
I tried not to and the webpage told me it was compulsory. I did it, received e-mail confirmation but the orange button ( I am afraid I was "phished" ) at the page does not respond ... and I cannot download Horos.
Any help, please ?
Jose M Palomo

**Comment by jensen0914** [comment]
You can grab Horos directly from this link: https://horosproject.org/horos-content/

You probably want one of these versions:

- Horos3.3.6.dmg (built for Intel, last "official" release)
- Horos4.0.0RC5.dmg (built for Intel, updates to handle newer, but not newest, versions of macOS)
- Horos4.0.0RC5_Apple.dmg (same as one just above but built for ARM/M1/M2 chips)

Regards,

Todd Jensen, PhD
Jensen Informatics LLC

**Comment by jensen0914** [comment]
And I don't think you have been phished. Purview is still taking donations but that is optional for using Horos. You should contact Purview directly if you need a receipt of some validation you were not phished.

**Comment by JoseMPalomo** [comment]
I do think you very much, Todd. Horos works now perfect and numbers, angles and areas read now perfectly clear and not in that strange letters maybe coming from some asian alphabet. [Horos4.0.0RC5.dmg] was the solution.
I mentioned my doubts about pishing because I did not understand why shoold I affiliate to PayPal afteer having afforded my MasterCard data. It's Ok now.
Thanks again,
Jose M Palomo
Hosp General Univ. Castelló

**Comment by JoseMPalomo** [comment]
Dear Todd,

	I cannot find anymore the webpage through which I made my question and you solved it … to pose another question.

	I don’t know whether I am or not allowed to put you another double question. I downloaded my Horos 4.0 from the webpage you told me and it works perfectly well but:

Horos collapses and closes itself the moment I pass from the 2-D Viewer to the 3D MPR view, but it works fine at the 3D Volume Rendering.
When I finish my 3D Volume Rendering and click Export/Export to Movie, it actually does it but sending the image ( a shoulder ) to an eccentrically awkward position, as I show you on the clip attached.
Can you help me ?
	My best regards,

	Jose M Palomo

￼

**Comment by jensen0914** [comment]
Horos, as far as I know, does not have anyone actively fixing issues and I am engaged with other projects. I suggest the following routes:

1. Purview offers support for payment. https://horosproject.org/professional-support
2. There is a Google Groups for Horos users that may have someone who has found a workaround for the same issue: https://groups.google.com/g/horos-project
3. Switch to an alternative viewer built on the same codebase that is more actively updated such as OsiriX or OsiriX Lite (http://www.osirix-viewer.com/) or Miele-LXIV (https://dicom.3utilities.com/viewer.php).

Todd Jensen, PhD
Jensen Informatics LLC

**Comment by JoseMPalomo** [comment]
Thanks vey much, Todd,

	Jose M Palomo
	Hospital General Universitari Castelló
