### ISSUE TITLE
freezing MPR

### ISSUE THREAD

**Issue by efnikos2000** [horosproject/horos#78]
Vey often the program fail to load series for MPR and the spin ball appears.
![2016-03-10 16 13 47](https://cloud.githubusercontent.com/assets/14727181/13671988/84c8307e-e6db-11e5-8d52-0251bee0cb3a.png)

**Comment by fvpolpeta** [comment]
We have this nightly build:

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos.app.Nightly%2020160422_161824.zip

Try it and let us know if the problem remains

BR

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze
