### ISSUE TITLE
I can edit the series number but the thumbnails and order do not change in Horos

### ISSUE THREAD

**Issue by chrisgdclarke** [horosproject/horos#80]
Within a study I am able to edit the metadata but when I change the series number (to re-order series) the series do not re-order within Horos.  Is this a known bug?  Pretty essential this is fixed if I'm to use the software for teaching!

Chris

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon. 

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards
