### ISSUE TITLE
can not open viewer

### ISSUE THREAD

**Issue by Jirasak19** [horosproject/horos#81]
I can import images , can view them from small preview screen but can not open them so I can not do any thing about them.
Please help.
Thank you.

**Comment by fvpolpeta** [comment]
Please provide us with an anonymized sample of your dataset.

**Comment by fvpolpeta** [comment]
We have this nightly build:

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos.app.Nightly%2020160422_161824.zip

Try it and let us know if the problem remains

BR

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze
