### ISSUE TITLE
Horos 1.1.7

### ISSUE THREAD

**Issue by jbmcan** [horosproject/horos#82]
Changing between series and opening, even with a single image, is very slow.  A lot of spinning balls.  Macbook with 16 Gb RAM and 30 Gb free disc space, my database is 120 Gb, is that an issue?

thank you

**Comment by fvpolpeta** [comment]
The image codecs in Horos are all open source, and not optimized for fast image manipulation. We are working to enhance this performance. Thanks for your feedback.

Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon. 

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards
