### ISSUE TITLE
Editing patient name corrupts some of the slices in a 3D data set

### ISSUE THREAD

**Issue by normandrobert** [horosproject/horos#84]
Puzzled by a corrupted 3D data set I pulled from my dcm4chee archive, I reloaded  the original directory containing DICOM files into Horos and discovered that editing a patient name in Horos v1.1.7 corrupted some data slices that looked fine before renaming. Can provide link to data...

**Comment by fvpolpeta** [comment]
We have this nightly build:

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos.app.Nightly%2020160422_161824.zip

Try it and let us know if the problem remains

BR

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze
