### ISSUE TITLE
Horos not start: spinning ball, can't fix with uninstall and re-download

### ISSUE THREAD

**Issue by jjabrams** [horosproject/horos#85]
When starting Horos, after a long delay I am asked if I want to use Protected mode etc - all three options fail, with 'application not responding' message; have to force call.  I've uninstalled using CleanMyMac and even downloading the recently uploaded nightly build does not fix.  Any idea?

**Comment by fvpolpeta** [comment]
Please try this nightly build and let us know how it performs.

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos.app.Nightly%2020160422_161824.zip

BR

**Comment by jjabrams** [comment]
Hi, I've tried this build and have had no luck with it. Same issue despite removing all traces of Horos from the system including the 'Horos Data' folder.

**Comment by fvpolpeta** [comment]
Please, clarify a bit:

You are always requested to start in protect mode?

**Comment by jjabrams** [comment]
![monosnap 2016-04-24 15-16-12](https://cloud.githubusercontent.com/assets/9367623/14768089/7f9aca18-0a2f-11e6-9981-e3ca25cf7416.jpg)

Either nothing happens at all, or I get the above dialog box.

Choosing any option does not lead to any success

**Comment by fvpolpeta** [comment]
Please try to remove the following files/dirs:

~/Library/Preferences/com.horosproject.horos.plist
~/Library/Cookies/com.horosproject.horos.binarycookies
~/Library/Caches/com.horosproject.horos
~/Library/Application Support/Horos

( ~ = User home directory)

**Comment by jjabrams** [comment]
Great - that seemed to fix it: now loads back up - many thanks!

**Comment by fvpolpeta** [comment]
Nice.

New nightly build:

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos.app.Nightly%2020160424_205640.zip

BR

**Comment by lohikarhu** [comment]
On 10.11, I get a similar problem, after I added a new set of files... tried 3 different versions of Horos, and it just hangs with the beachball spinning. To add to strangeness, OsirixLite v 3.9, has no problem with this file set... the file set contains several non-dicom files, including a 3d volumised file, and a couple of radiologist reports.

Deleting the files suggested allows Horos to start, but just clicking on the "bad" folder seems to hang it ...
