### ISSUE TITLE
Commit 0e69d7b breaks BrowserMatrix cells' representedObject values

### ISSUE THREAD

**Issue by aglv** [horosproject/horos#87]
With commit 0e69d7b, once cells in the BrowserController's matrix are clicked, their representedObject is reassigned to the current databaseOutline selected study. This doesn't make sense.
Why reassign the representedObject, when the current value properly points to the corresponding DicomStudy/DicomImage objectID? And why reassign it with the DicomStudy objectID?
Would you please consider reestablishing the previous behavior?

**Comment by aglv** [comment]
Additionally, the image is reassigned to the study's thumbnail.... And the title.... basically, things are broken :(

**Comment by fvpolpeta** [comment]
This will be revisited when possible. There might be redundancy and no-sense statements, but we were facing a strange problem that thumbnails were just missing when button was clicked. I appreciate your help on making this works using the original implementation and push a pull request.

The issues with legacy XIB files has been traumatic. Porting Horos to El Capitan has improved stability based on  feedbacks we are receiving, but UI misbehaviours are being caused and will be gradually fixed.

For instance, there were cases that I had to remove the Window object from the XIB and add it again, past all other components back, and then the expected window behavior was obtained. Crazy stuff.

Thanks again for your help.

BR

**Comment by aglv** [comment]
OK, congratulations on the ElCap upgrade! I'll try and fix things I notice.

**Comment by aglv** [comment]
My commit 89e169c, part of #86, fixes this for me.
