### ISSUE TITLE
Horos won't start

### ISSUE THREAD

**Issue by madanjou** [horosproject/horos#90]
I've downloaded Horos recently and started using it. It was working normally, but it won't start again. I've tried over several days without success.

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze

**Comment by madanjou** [comment]
Thanks. Horos was able to start after I restarted my iMac. I'll try this build if the problem recurs.
