### ISSUE TITLE
Horos - PDFtoDICOM plugin is not loaded after installation

### ISSUE THREAD

**Issue by lk7777** [horosproject/horos#91]
Horos - 1.1.7
Plugin PDFtoDICOM - 2.1
PDFtoDICOM plugin is not loaded after installation. It is not listed under Plugins-Database.

**Comment by riversde** [comment]
use osirix lite to download and search the plugin on /Library/ApplicationSupport/OsirixLite/Plugins, copy and paste it inside same folder but Horos plugin.  It should work.

**Comment by fvpolpeta** [comment]
Please, use this build of version 2.0.0, planned to be released next week:

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

**Comment by riversde** [comment]
I can confirm build 2.0.0 and PDFtoDicom plugin works

Thanks
