### ISSUE TITLE
Editing Metadata or Anonymizing unusual behavior

### ISSUE THREAD

**Issue by cryanvmd** [horosproject/horos#92]
when using the metadata editor to edit patient data (patient name, patient ID) or when using the Anonymize feature to perform same function of changing the patient data for a CT data set multiple images in the data set are deleted.  Please see attached image.  
![img_1457](https://cloud.githubusercontent.com/assets/16805104/15396032/45a1aef8-1da8-11e6-974b-6cac3474670f.JPG)
![img_1457](https://cloud.githubusercontent.com/assets/16805104/15396042/52e0e41c-1da8-11e6-8749-9af8ff9b4ef9.JPG)

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze
