### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by aglv** [horosproject/horos#93]
Hey,

I just synced the latest changes from the horos branch and can't compile because of these errors:

```
> /Users/ale/Work/Horos/PluginManager.m:1547:39: Use of undeclared identifier 'HOROS_PLUGIN_LIST_URL'
> /Users/ale/Work/Horos/PluginManager.m:1553:36: Use of undeclared identifier 'HOROS_PLUGIN_LIST_ALT_URL'
> /Users/ale/Work/Horos/PluginManager.m:1609:39: Use of undeclared identifier 'OSIRIX_PLUGIN_LIST_URL'
> /Users/ale/Work/Horos/PluginManager.m:1615:36: Use of undeclared identifier 'OSIRIX_PLUGIN_LIST_ALT_URL'
```

**Comment by fvpolpeta** [comment]
Please, run the Unzip Binaries again. It must solve. I will remove these headers from these zip files. No reason for that.

**Comment by aglv** [comment]
Did that, didn't fix the error... Just tried again with Cleanup Binaries and Unzip Binaries, is now ok 👍
