### ISSUE TITLE
Crash when pulling Remote Osirix Database

### ISSUE THREAD

**Issue by Naaf83** [horosproject/horos#99]
Hello,
Our server is a 64bit osirix, my device is equipped with Horos V1.1.7
I face a crash -of Horos- every time i try to load studies on the remote Osirix Server (with in local network).

When i pull studies via osirix on my laptop i get no error.

Thanks in advance,
Nawaf
[Horos_Crash_Remote_Server.txt](https://github.com/horosproject/horos/files/289409/Horos_Crash_Remote_Server.txt)

**Comment by riversde** [comment]
Also, I have this issue with Nightly Build 2.0 database error with Osirix Lite 7.5 database

[horos2.0hang.txt](https://github.com/horosproject/horos/files/291475/horos2.0hang.txt)

**Comment by fvpolpeta** [comment]
Please, try this Release Candidate build:

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos2.0.0RC2.dmg

If problem persists, write/attach (text/video/images) a step-by-step of how we can reproduce it.

Thanks

**Comment by riversde** [comment]
RC2 work flawlessly on same database. So database issue is fix.   Also as an "Incidental" finding the preferences tab show the lock icon, but you can change settings.  Touching the lock crash the app.

**Comment by fvpolpeta** [comment]
Tks.

The issue with the Preferences Locker is fixed here:

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

BR

**Comment by Naaf83** [comment]
Thank you very much
